const V13_API='https://iytjxruxpvwjjhbndkzo.supabase.co/functions/v1/kibernetic-data';
const V12_profile=profile,V12_saveProfile=saveProfile,V12_select=select,V12_analyze=analyze;
S.usd=S.usd||{};S.newsMeta=S.newsMeta||{};
const v13api=async(type,params={})=>{const u=new URL(V13_API);u.searchParams.set('type',type);Object.entries(params).forEach(([k,v])=>v!=null&&u.searchParams.set(k,String(v)));return J(u.toString())};
const norm=s=>String(s||'').trim().toLowerCase();
const sameToken=(a,b)=>{const aa=norm(a?.address||a?.baseToken?.address),bb=norm(b?.address||b?.baseToken?.address);if(aa&&bb&&aa===bb)return true;return norm(a?.symbol||a?.baseToken?.symbol)===norm(b?.symbol||b?.baseToken?.symbol)&&norm(a?.name||a?.baseToken?.name)===norm(b?.name||b?.baseToken?.name)};
function dedupeWatch(){const out=[];for(const x of S.watch){const i=out.findIndex(y=>sameToken(x,y));if(i<0)out.push(x);else{const keep=(num(x.liq)>num(out[i].liq)||num(x.updated)>num(out[i].updated))?x:out[i];out[i]={...out[i],...keep}}}S.watch=out;localStorage.setItem('kiber_watch_v12',JSON.stringify(S.watch))}
function injectV13(){if(!$('themeSelect')){$('profilePanel').insertAdjacentHTML('beforeend',`<div class="profile-section-title">Aspetto & Informazioni</div><div class="theme-controls"><div class="field"><label>Tema pagina</label><select id="themeSelect"><option value="dark">Scuro</option><option value="light">Chiaro</option><option value="blue">Blu</option><option value="cyan">Celeste</option><option value="kiber">Kiber</option></select></div><div class="field"><label>Colore principale</label><input id="accentColor" type="color" value="#1677ff"></div><div class="field"><label>News da mostrare</label><select id="newsImpactMin"><option value="0">Tutte</option><option value="45">Impatto medio + alto</option><option value="70">Solo alto impatto</option></select></div><div class="field"><label>Motivazioni news</label><select id="newsWhy"><option value="1">Mostra sempre</option><option value="0">Compatte</option></select></div></div>`)}
if(!$('intelWrap')){$('analysisOutput').insertAdjacentHTML('afterend',`<div class="intel-wrap" id="intelWrap"><div class="head"><div><h3>Intelligence spiegata</h3><div class="small">Dati osservati, possibili motivazioni e idee da verificare</div></div><span class="confidence" id="intelConfidence">In attesa</span></div><div class="intel-grid" id="intelDrivers"><div class="driver"><b>Seleziona un token</b><small>Il laboratorio costruirà l'analisi usando mercato, settore, storico, news, dollaro e rischio.</small></div></div><div class="evidence-box"><b>News collegate al token / settore</b><div id="tokenNewsEvidence" class="small">Nessuna analisi ancora.</div></div><div class="idea-box"><b>Idee da verificare</b><div id="tokenIdeas" class="small">Le idee sono piste di ricerca, non previsioni.</div></div></div>`)}
const ns=document.querySelector('#newsList')?.parentElement;if(ns&&!$('newsMethod')){const d=document.createElement('div');d.id='newsMethod';d.className='news-method';d.textContent='Le news sono ordinate per impatto euristico. Impatto non significa causalità: apri la fonte e confronta i dati.';ns.insertBefore(d,$('newsList'))}}
function applyTheme(){const p=S.profile||{},t=p.theme||'dark';document.body.classList.remove('theme-dark','theme-light','theme-blue','theme-cyan','theme-kiber');document.body.classList.add('theme-'+t);document.documentElement.style.setProperty('--blue',p.accent||'#1677ff');if($('themeSelect'))$('themeSelect').value=t;if($('accentColor'))$('accentColor').value=p.accent||'#1677ff';if($('newsImpactMin'))$('newsImpactMin').value=String(p.newsImpactMin??0);if($('newsWhy'))$('newsWhy').value=String(p.newsWhy??1)}
profile=function(){V12_profile();applyTheme()};
saveProfile=function(){const t=$('themeSelect')?.value||S.profile.theme||'dark',a=$('accentColor')?.value||S.profile.accent||'#1677ff',m=num($('newsImpactMin')?.value),w=num($('newsWhy')?.value);V12_saveProfile();S.profile={...S.profile,theme:t,accent:a,newsImpactMin:m,newsWhy:w};localStorage.setItem('kiber_profile_v12',JSON.stringify(S.profile));applyTheme();renderNews(document.querySelector('.tab.active')?.dataset.filter||'all')};
function watchIndexFor(p){return S.watch.findIndex(x=>sameToken(x,p))}
function updateWatchState(){if(!S.selected)return;const i=watchIndexFor(S.selected),b=$('watchBtn');if(!b)return;b.textContent=i>=0?'Già in osservazione · aggiorna dati':'Aggiungi alla lista osservazione';let s=$('watchState');if(!s){b.insertAdjacentHTML('afterend','<div class="watch-state" id="watchState"></div>');s=$('watchState')}s.textContent=i>=0?'Questo token è già presente. Un nuovo clic aggiorna i dati senza creare duplicati.':'Il token verrà salvato una sola volta usando contratto e identità progetto.'}
function v13AddWatch(){const p=S.selected;if(!p)return;const i=watchIndexFor(p),item={key:norm(p.baseToken?.address)||norm(p.baseToken?.symbol)+'|'+norm(p.baseToken?.name),address:p.baseToken?.address,pairAddress:p.pairAddress,symbol:p.baseToken?.symbol,name:p.baseToken?.name,sector:sector(p),price:num(p.priceUsd),change24:num(p.priceChange?.h24),liq:num(p.liquidity?.usd),vol:num(p.volume?.h24),risk:risk(p),note:$('selectedNote').value.trim(),analysis:$('analysisOutput').textContent,intelligence:buildIntelText(),updated:Date.now()};if(i>=0){S.watch[i]={...S.watch[i],...item};localStorage.setItem('kiber_watch_v12',JSON.stringify(S.watch));renderWatch();updateWatchState()}else{S.watch.push(item);localStorage.setItem('kiber_watch_v12',JSON.stringify(S.watch));renderWatch();updateWatchState();addAlert(`${item.symbol} aggiunto alla lista osservazione`)}}
select=function(i){V12_select(i);updateWatchState();setTimeout(buildIntel,50)};
analyze=function(){V12_analyze();buildIntel()};
function relevantNews(p){if(!p)return[];const sy=norm(p.baseToken?.symbol),nm=norm(p.baseToken?.name),sec=sector(p).toLowerCase(),cat=sec==='defi'?'defi':sec==='ai'?'ai':sec==='meme'?'meme':sec==='layer 1'?'bnb':'token';return S.news.map(n=>{const t=norm(n.title),direct=(sy&&new RegExp(`\\b${sy.replace(/[^a-z0-9]/g,'')}\\b`,'i').test(t))||(nm&&nm.length>3&&t.includes(nm)),sectorHit=n.category===cat||n.category==='bnb';return{...n,relevance:direct?3:sectorHit?1:0}}).filter(n=>n.relevance>0).sort((a,b)=>b.relevance-a.relevance||num(b.impactScore)-num(a.impactScore)).slice(0,6)}
function marketDrivers(p){if(!p)return[];const c=num(p.priceChange?.h24),liq=num(p.liquidity?.usd),vol=num(p.volume?.h24),buys=num(p.txns?.h24?.buys),sells=num(p.txns?.h24?.sells),tot=buys+sells,flow=tot?(buys-sells)/tot*100:0,vl=liq?vol/liq:0,sec=sector(p),group=S.pairs.filter(x=>sector(x)===sec),secAvg=group.length?group.reduce((a,x)=>a+num(x.priceChange?.h24),0)/group.length:0,rn=relevantNews(p),d=[];d.push({title:'Prezzo & momentum',text:`24h ${c>=0?'+':''}${fmt(c,2)}%. Il token ${c-secAvg>=0?'sta sovraperformando':'sta sottoperformando'} il campione ${sec} di ${fmt(Math.abs(c-secAvg),2)} punti percentuali.`});d.push({title:'Liquidità & volume',text:`Liquidità ${short(liq)}, volume 24h ${short(vol)}. Rapporto volume/liquidità ${fmt(vl,2)}x: ${vl>3?'attività molto elevata rispetto alla profondità':'attività da leggere insieme alla profondità del pool'}.`});d.push({title:'Pressione transazioni',text:`Buy ${fmt(buys,0)} / Sell ${fmt(sells,0)}. Squilibrio ${flow>=0?'+':''}${fmt(flow,1)}%. È un indizio di flusso, non prova della direzione futura.`});d.push({title:'Contesto settore',text:`Settore ${sec}: media 24h del campione ${secAvg>=0?'+':''}${fmt(secAvg,2)}% su ${group.length||0} token disponibili nel feed.`});if(S.usd?.dxy)d.push({title:'Dollaro / macro',text:`USD Strength Proxy ${fmt(S.usd.dxy.price,2)} (${S.usd.dxy.change>=0?'+':''}${fmt(S.usd.dxy.change,2)}%). Va usato come contesto macro, non come causa automatica del movimento.`});d.push({title:'News & eventi',text:`${rn.length} notizie collegate per token o settore; ${rn.filter(x=>num(x.impactScore)>=70).length} ad alto impatto euristico. Aprire le fonti prima di attribuire causalità.`});return d}
function buildIntelText(){const p=S.selected;if(!p)return'Nessun token selezionato.';return marketDrivers(p).map(x=>`${x.title}: ${x.text}`).join(' | ')}
function buildIntel(){const p=S.selected;if(!p||!$('intelDrivers'))return;const d=marketDrivers(p),rn=relevantNews(p),evidence=d.length+(rn.length?1:0)+(S.usd?.dxy?1:0),conf=evidence>=7?'Alta copertura dati':evidence>=5?'Media copertura dati':'Copertura dati limitata';$('intelConfidence').textContent=conf;$('intelDrivers').innerHTML=d.map(x=>`<div class="driver"><b>${esc(x.title)}</b><small>${esc(x.text)}</small></div>`).join('');$('tokenNewsEvidence').innerHTML=rn.length?rn.map(n=>`<div class="news-intel"><div class="news-top"><div><b>${esc(n.title)}</b><div class="meta">${esc(n.source||'Fonte')} · ${esc(n.sourceType||'')}</div></div><span class="impact ${num(n.impactScore)>=70?'high':num(n.impactScore)>=45?'med':'low'}">${esc(n.impact||'Impatto')} ${num(n.impactScore)}/100</span></div><div class="news-why">Perché conta: ${esc(n.why||'Da verificare nel contesto del token.')}</div></div>`).join(''):'Nessuna news direttamente collegata nel feed corrente.';const ideas=[],liq=num(p.liquidity?.usd),vol=num(p.volume?.h24),c=Math.abs(num(p.priceChange?.h24)),b=num(p.txns?.h24?.buys),s=num(p.txns?.h24?.sells);if(liq<1e5)ideas.push('Verificare altri pool e la concentrazione della liquidità: movimenti piccoli possono produrre grandi variazioni.');if(liq&&vol/liq>3)ideas.push('Controllare se il volume elevato è distribuito nel tempo o concentrato in poche operazioni.');if(c>10&&Math.abs(b-s)/(b+s||1)<.1)ideas.push('Prezzo molto mosso ma buy/sell quasi bilanciati: verificare profondità del book/pool e dimensione delle singole operazioni.');if(rn.some(n=>num(n.impactScore)>=70))ideas.push('Aprire le fonti delle news ad alto impatto e confrontare l’orario con inizio del movimento sul grafico.');ideas.push('Confrontare il token con BNB e con la media del suo settore per separare movimento specifico da movimento generale.');$('tokenIdeas').innerHTML='<ul>'+ideas.map(x=>`<li>${esc(x)}</li>`).join('')+'</ul>'}
async function v13Market(){try{const d=await v13api('market'),seen=new Set();S.pairs=(d.pairs||[]).filter(p=>{const k=norm(p.baseToken?.address)||norm(p.baseToken?.symbol)+'|'+norm(p.baseToken?.name);if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>num(b.liquidity?.usd)-num(a.liquidity?.usd));applyFilters();renderSectors();$('liveStatus').textContent='V13 INTELLIGENCE'}catch(e){loadMarket()}}
async function v13Search(){const q=$('tokenSearch').value.trim();if(!q)return;$('rows').innerHTML='<tr><td colspan="7" class="small">Ricerca live...</td></tr>';try{const d=await v13api('search',{q}),seen=[];S.pairs=(d.pairs||[]).filter(p=>p.chainId==='bsc').sort((a,b)=>num(b.liquidity?.usd)-num(a.liquidity?.usd)).filter(p=>{if(seen.some(x=>sameToken(x,p)))return false;seen.push(p);return true});applyFilters();renderSectors();if(S.filtered[0])select(S.pairs.indexOf(S.filtered[0]))}catch(e){searchTokens()}}
loadHistory=async function(period){if(!S.selected)return;S.period=period;qa('.time').forEach(b=>b.classList.toggle('active',b.dataset.period===period));$('historyHint').textContent='Caricamento storico...';try{const d=await v13api('history',{pool:S.selected.pairAddress,period}),a=(d.ohlcv||[]).slice().reverse(),cl=a.map(x=>+x[4]).filter(Number.isFinite);if(!cl.length)throw Error();draw('historyLine',cl);const ch=(cl.at(-1)-cl[0])/cl[0]*100;$('historyHint').textContent=`${period.toUpperCase()} · ${cl.length} punti · ${d.source||'storico'}`;$('periodStats').textContent=`${ch>=0?'+':''}${fmt(ch,2)}% · ${usd(cl[0],8)} → ${usd(cl.at(-1),8)}`;buildIntel()}catch(e){$('historyHint').textContent='Storico non disponibile per questo pool/periodo.';$('periodStats').textContent='—'}};
renderNews=function(f){const min=num(S.profile.newsImpactMin),why=S.profile.newsWhy!==0,a=S.news.filter(n=>(f==='all'||n.category===f)&&num(n.impactScore)>=min).slice(0,15);$('newsList').innerHTML=a.length?a.map(n=>`<div class="news-item news-intel"><div class="news-top"><div><a href="${esc(n.url)}" target="_blank" rel="noopener">${esc(n.title)}</a><div class="meta">${esc(n.source||'Fonte')} · ${n.published?new Date(n.published).toLocaleString('it-IT'):''} · <span class="source-badge">${esc(n.sourceType||'Fonte')}</span></div></div><span class="impact ${num(n.impactScore)>=70?'high':num(n.impactScore)>=45?'med':'low'}">${esc(n.impact||'Basso')} ${num(n.impactScore)}/100</span></div>${why?`<div class="news-why"><b>Perché conta:</b> ${esc(n.why||'Da contestualizzare con i dati di mercato.')}</div>`:''}</div>`).join(''):'<div class="small">Nessuna news con questi filtri.</div>'};
function newsNotif(items){const key='kiber_news_seen_v13',old=JSON.parse(localStorage.getItem(key)||'null'),ids=items.map(x=>norm(x.title));if(!old){localStorage.setItem(key,JSON.stringify(ids.slice(0,100)));return}const set=new Set(old),fresh=items.filter(x=>!set.has(norm(x.title))&&num(x.impactScore)>=70);for(const n of fresh.slice(0,3)){const enabled=n.category==='policy'?S.profile.notifPolicy:n.category==='macro'?S.profile.notifMacro:n.category==='bnb'?S.profile.notifChainNews:n.category==='defi'?S.profile.notifDefi:n.category==='ai'?S.profile.notifAI:n.category==='meme'?S.profile.notifMeme:false;if(enabled)addAlert(`News ${n.impact}: ${n.title}`)}localStorage.setItem(key,JSON.stringify([...ids,...old].slice(0,150)))}
loadNews=async function(){try{const d=await v13api('news');S.news=d.items||[];S.newsMeta=d;renderNews(document.querySelector('.tab.active')?.dataset.filter||'all');newsNotif(S.news);buildIntel()}catch(e){$('newsList').innerHTML='<div class="small">News temporaneamente non disponibili.</div>'}};
loadUsd=async function(){try{const d=await v13api('usd');S.usd=d;if(d.dxy){$('dxyValue').textContent=fmt(d.dxy.price,2);$('dxyChange').textContent=(d.dxy.change>=0?'+':'')+fmt(d.dxy.change,2)+'% · proxy giornaliero'}$('usdEur').textContent=fmt(d.usdEur,4);$('usdEurTime').textContent=(d.live?'proxy live · ':'')+(d.date||'riferimento');buildIntel()}catch(e){$('usdEur').textContent='—'}};
loadSec=async function(){try{const d=await v13api('sec');S.sec=d.items||[];$('secList').innerHTML=S.sec.length?S.sec.slice(0,10).map(n=>`<div class="news-item news-intel"><div class="news-top"><div><a href="${esc(n.url)}" target="_blank" rel="noopener">${esc(n.title)}</a><div class="meta">SEC.gov · ${n.published?new Date(n.published).toLocaleString('it-IT'):''}</div></div><span class="impact ${num(n.impactScore)>=70?'high':num(n.impactScore)>=45?'med':'low'}">${esc(n.impact)} ${num(n.impactScore)}/100</span></div><div class="news-why"><b>Perché conta:</b> ${esc(n.why)}</div></div>`).join(''):'<div class="small">Nessun elemento SEC nel feed corrente.</div>';buildIntel()}catch(e){$('secList').innerHTML='<div class="small">Feed SEC temporaneamente non disponibile.</div>'}};
localKiber=function(q){const p=S.selected,l=norm(q),rn=relevantNews(p);if(/news|notiz/.test(l))return p?`Per ${p.baseToken?.symbol} ho ${rn.length} news pertinenti nel feed. ${rn.slice(0,3).map(n=>`${n.impact} impatto: ${n.title}. Perché conta: ${n.why}`).join(' | ')||'Nessuna news diretta: usa settore e macro come contesto.'}`:`News caricate: ${S.news.length}. Posso collegarle meglio dopo che selezioni un token.`;if(/perch|motivo|influen|analizz/.test(l)&&p)return buildIntelText();if(/dollar|dollaro|usd/.test(l))return`USD/EUR ${$('usdEur').textContent}; USD Strength ${$('dxyValue').textContent}. È contesto macro, non causa automatica.`;if(/sec|regol/.test(l))return`SEC Monitor ha ${S.sec.length} elementi. Per ogni comunicato mostro fonte, impatto euristico e perché può contare; l’effetto sul token va verificato.`;if(/resoconto/.test(l))return reportText()+'\n\nINTELLIGENCE:\n'+buildIntelText();return p?buildIntelText():'Scegli un token: ti spiego dati, motivazioni possibili, news pertinenti e cosa verificare.'};
function bindV13(){dedupeWatch();injectV13();applyTheme();renderWatch();$('watchBtn').onclick=v13AddWatch;$('saveAnalysisData').onclick=v13AddWatch;$('saveProfile').onclick=saveProfile;$('refreshMarket').onclick=v13Market;$('searchBtn').onclick=v13Search;$('tokenSearch').onkeydown=e=>e.key==='Enter'&&v13Search();$('refreshNews').onclick=loadNews;$('refreshUsd').onclick=loadUsd;$('refreshSec').onclick=loadSec;$('analyzeMarket').onclick=analyze;v13Market();loadNews();loadUsd();loadSec();updateWatchState()}
bindV13();