// Kibernetic BNB Intelligence V14
const V14_API='https://iytjxruxpvwjjhbndkzo.supabase.co/functions/v1/kibernetic-data';
S.newProjects=S.newProjects||[];S.hubFilter='all';
const V14_renderWatch=renderWatch,V14_applyFilters=applyFilters,V14_renderSectors=renderSectors;
const v14api=async(type,params={})=>{const u=new URL(V14_API);u.searchParams.set('type',type);Object.entries(params).forEach(([k,v])=>v!=null&&u.searchParams.set(k,String(v)));return J(u.toString())};
const sectorDefs={
'DeFi':{title:'Finanza decentralizzata',what:'Protocolli per scambio, prestito, staking, liquidità e rendimento senza intermediari tradizionali.',watch:'TVL, liquidità, volumi DEX, utilizzo, incentivi, exploit e regolamentazione.'},
'AI':{title:'AI & Compute',what:'Progetti che uniscono blockchain, agenti AI, dati, modelli, calcolo o infrastruttura per intelligenza artificiale.',watch:'Adozione reale, domanda di compute, partnership, emissioni token e narrativa AI.'},
'Meme':{title:'Meme & Community',what:'Token guidati soprattutto da attenzione, community, liquidità e narrativa sociale.',watch:'Liquidità, concentrazione holder, volume, velocità dei flussi e rischio di inversioni rapide.'},
'Gaming':{title:'Gaming & Metaverse',what:'Token collegati a giochi, asset digitali, marketplace e infrastrutture per gaming on-chain.',watch:'Utenti, attività in-game, token economy, retention, release e partnership.'},
'Infrastructure':{title:'Infrastructure',what:'Protocolli che forniscono rete, bridge, tooling, servizi o componenti di base all’ecosistema.',watch:'Utilizzo della rete, integrazioni, sicurezza, fee, crescita developer e dipendenze tecniche.'},
'RWA':{title:'Real World Assets',what:'Token e protocolli che rappresentano o collegano asset e flussi finanziari del mondo reale alla blockchain.',watch:'Regole, collateral, qualità degli asset, domanda istituzionale, tassi e liquidità.'},
'Data':{title:'Data & Oracle',what:'Progetti che raccolgono, indicizzano, distribuiscono o verificano dati per applicazioni blockchain.',watch:'Clienti, richieste dati, integrazioni, sicurezza degli oracle e crescita dell’utilizzo.'},
'Layer 1':{title:'Layer 1',what:'Blockchain di base che gestiscono transazioni, sicurezza e applicazioni del proprio ecosistema.',watch:'Transazioni, fee, utenti, validatori, TVL, stablecoin e sviluppo applicazioni.'},
'Altro':{title:'Altri progetti',what:'Token non ancora classificati con sufficiente affidabilità in uno dei comparti principali.',watch:'Prima di interpretarli serve capire funzione del progetto, tokenomics, liquidità, team e casi d’uso.'}
};
function v14Inject(){
 const hero=document.querySelector('.hero p');if(hero&&!$('flashNews'))hero.insertAdjacentHTML('afterend',`<div class="flash-news" id="flashNews"><div class="flash-kicker">ULTIMA NOTIZIA DISPONIBILE</div><div class="flash-title" id="flashTitle">Caricamento notizie...</div><div class="flash-meta"><span id="flashSource">—</span><span id="flashTime">—</span><span id="flashImpact" class="v14-chip">—</span></div><div class="flash-why" id="flashWhy">La piattaforma mostra la notizia più recente disponibile e spiega perché può essere rilevante.</div></div>`);
 const market=$('rows')?.closest('.card');if(market&&!$('newProjectsCard'))market.insertAdjacentHTML('afterend',`<section class="card s12" id="newProjectsCard"><div class="head"><div><h2>Nuovi progetti BNB Chain</h2><div class="small">Nuovi pool rilevati. “Nuovo” non significa automaticamente affidabile.</div></div><button class="btn" id="refreshNewProjects">Aggiorna nuovi</button></div><div class="new-grid" id="newProjectsGrid"><div class="small">Caricamento nuovi progetti...</div></div></section>`);
 const watch=$('watchCards')?.closest('.card');if(watch&&!$('labHub'))watch.insertAdjacentHTML('beforebegin',`<section class="card s12 lab-hub" id="labHub"><div class="head"><div><h2>Laboratorio Centrale</h2><div class="small">Le monete osservate vengono confrontate continuamente per trend, rischio, settore e variazione.</div></div><span class="small" id="hubUpdated">—</span></div><div class="hub-kpis"><div class="hub-kpi"><span>Monitorate</span><b id="hubTotal">0</b></div><div class="hub-kpi"><span>Up 24h</span><b class="up" id="hubUp">0</b></div><div class="hub-kpi"><span>Down 24h</span><b class="down" id="hubDown">0</b></div><div class="hub-kpi"><span>Rischio alto</span><b id="hubHighRisk">0</b></div><div class="hub-kpi"><span>Settori</span><b id="hubSectors">0</b></div></div><div class="hub-controls" id="hubControls"><button class="active" data-hub="all">Tutte</button><button data-hub="up">Up</button><button data-hub="down">Down</button><button data-hub="risk">Rischio alto</button></div><div class="hub-list" id="hubList"><div class="small">Aggiungi token alla lista osservazione.</div></div></section>`);
 const hist=document.querySelector('.history-box');if(hist&&!$('graphIntel'))hist.insertAdjacentHTML('afterend',`<div id="graphIntel"><div class="graph-intel"><div class="graph-stat"><span>Direzione periodo</span><b id="giDirection">—</b></div><div class="graph-stat"><span>Minimo osservato</span><b id="giLow">—</b></div><div class="graph-stat"><span>Massimo osservato</span><b id="giHigh">—</b></div><div class="graph-stat"><span>Volatilità</span><b id="giVol">—</b></div><div class="graph-stat"><span>Max drawdown</span><b id="giDD">—</b></div></div><div class="graph-story" id="graphStory">Il grafico verrà accompagnato da una lettura del movimento.</div></div>`);
 if(!$('detailOverlay'))document.body.insertAdjacentHTML('beforeend',`<div class="detail-overlay" id="detailOverlay"><div class="detail-sheet"><div class="detail-head"><div><div class="detail-kicker" id="detailKicker">Kibernetic Intelligence</div><h2 id="detailTitle">Dettaglio</h2></div><button class="btn" id="detailClose">Chiudi</button></div><div class="detail-theme"></div><div id="detailBody"></div></div></div>`);
 const newsCard=$('newsList')?.closest('.card');if(newsCard&&!$('newsSources'))newsCard.querySelector('.head')?.insertAdjacentHTML('beforeend','<div class="source-count" id="newsSources">Fonti: —</div>');
 $('refreshNewProjects').onclick=loadNewProjects;$('detailClose').onclick=closeDetail;$('detailOverlay').onclick=e=>{if(e.target===$('detailOverlay'))closeDetail()};qa('#hubControls button').forEach(b=>b.onclick=()=>{qa('#hubControls button').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.hubFilter=b.dataset.hub;renderHub()});
 document.querySelector('.eyebrow').textContent='BNB CHAIN INTELLIGENCE · V14';
}
function closeDetail(){$('detailOverlay')?.classList.remove('show')}
function showDetail(kicker,title,html){$('detailKicker').textContent=kicker;$('detailTitle').textContent=title;$('detailBody').innerHTML=html;$('detailOverlay').classList.add('show');window.scrollTo({top:window.scrollY})}
function ageText(d){if(!d)return'Data non disponibile';const ms=Date.now()-new Date(d).getTime();if(!Number.isFinite(ms))return'Data non disponibile';const h=Math.max(0,ms/36e5);return h<1?`${Math.round(h*60)} min fa`:h<24?`${Math.round(h)} ore fa`:`${Math.round(h/24)} giorni fa`}
function sectorNewsCategory(sec){return sec==='DeFi'?'defi':sec==='AI'?'ai':sec==='Meme'?'meme':sec==='Layer 1'?'bnb':'token'}
function sectorStats(sec){const a=S.pairs.filter(p=>sector(p)===sec),avg=a.length?a.reduce((z,p)=>z+num(p.priceChange?.h24),0)/a.length:0,up=a.filter(p=>num(p.priceChange?.h24)>0).length,down=a.filter(p=>num(p.priceChange?.h24)<0).length,vol=a.reduce((z,p)=>z+num(p.volume?.h24),0),liq=a.reduce((z,p)=>z+num(p.liquidity?.usd),0);return{a,avg,up,down,vol,liq}}
renderSectors=function(){const secs=[...new Set(S.pairs.map(sector))].filter(Boolean);$('sectorOutput').innerHTML=secs.length?`<div class="sector-summary-grid">${secs.map(sec=>{const st=sectorStats(sec),d=sectorDefs[sec]||sectorDefs.Altro;return`<div class="sector-summary sector-open" data-sec="${esc(sec)}"><h4>${esc(sec)} · ${esc(d.title)}</h4><div class="sector-move ${st.avg>=0?'up':'down'}">${st.avg>=0?'+':''}${fmt(st.avg,2)}%</div><p>${esc(d.what)}</p><div class="meta-row"><span>${st.a.length} token</span><span>Up ${st.up} / Down ${st.down}</span><span>Vol ${short(st.vol)}</span></div><button class="btn sector-open-btn" data-sec="${esc(sec)}">Apri settore</button></div>`}).join('')}</div>`:'Nessun settore disponibile.';bindSectorButtons()};
function bindSectorButtons(){qa('#sectorList button').forEach(b=>b.onclick=()=>openSector(b.dataset.sector));qa('[data-sec].sector-open,[data-sec].sector-open-btn').forEach(b=>b.onclick=e=>{e.stopPropagation();openSector(b.dataset.sec)})}
function openSector(sec){const st=sectorStats(sec),d=sectorDefs[sec]||sectorDefs.Altro,cat=sectorNewsCategory(sec),news=S.news.filter(n=>n.category===cat||sec==='Layer 1'&&n.category==='bnb').slice(0,5),topUp=[...st.a].sort((a,b)=>num(b.priceChange?.h24)-num(a.priceChange?.h24)).slice(0,5),topDown=[...st.a].sort((a,b)=>num(a.priceChange?.h24)-num(b.priceChange?.h24)).slice(0,5);const rows=a=>a.map(p=>`<div class="detail-row"><div><b>${esc(p.baseToken?.symbol)} · ${esc(p.baseToken?.name)}</b><div class="small">${usd(p.priceUsd,8)} · Liq ${short(p.liquidity?.usd)} · Vol ${short(p.volume?.h24)}</div></div><div><b class="${num(p.priceChange?.h24)>=0?'up':'down'}">${num(p.priceChange?.h24)>=0?'+':''}${fmt(p.priceChange?.h24,2)}%</b><br><button class="btn detail-token" data-address="${esc(p.baseToken?.address)}">Apri</button></div></div>`).join('');showDetail('REPARTO SETTORI',`${sec} · ${d.title}`,`<div class="detail-section"><div class="analysis-output"><b>Che cos’è</b><br>${esc(d.what)}<br><br><b>Cosa monitorare</b><br>${esc(d.watch)}</div></div><div class="detail-grid detail-section"><div class="detail-block"><span>Media 24h</span><b class="${st.avg>=0?'up':'down'}">${st.avg>=0?'+':''}${fmt(st.avg,2)}%</b></div><div class="detail-block"><span>Up / Down</span><b>${st.up} / ${st.down}</b></div><div class="detail-block"><span>Volume campione</span><b>${short(st.vol)}</b></div><div class="detail-block"><span>Liquidità campione</span><b>${short(st.liq)}</b></div><div class="detail-block"><span>Token analizzati</span><b>${st.a.length}</b></div><div class="detail-block"><span>Direzione</span><b>${st.avg>2?'Forza relativa':st.avg<-2?'Debolezza relativa':'Misto'}</b></div></div><div class="detail-section"><h3>Più forti 24h</h3><div class="detail-list">${rows(topUp)||'<div class="small">Nessun dato.</div>'}</div></div><div class="detail-section"><h3>Più deboli 24h</h3><div class="detail-list">${rows(topDown)||'<div class="small">Nessun dato.</div>'}</div></div><div class="detail-section"><h3>Notizie del comparto</h3><div class="detail-list">${news.map(n=>`<div class="detail-row"><div><b>${esc(n.title)}</b><div class="small">${esc(n.source||'Fonte')} · ${esc(n.why||'')}</div></div><span class="v14-chip">${esc(n.impact||'')}</span></div>`).join('')||'<div class="small">Nessuna notizia specifica nel feed corrente.</div>'}</div></div>`);qa('.detail-token').forEach(b=>b.onclick=()=>{const p=S.pairs.find(x=>norm(x.baseToken?.address)===norm(b.dataset.address));if(p)openTokenObject(p)})}
function openTokenObject(p){let i=S.pairs.findIndex(x=>sameToken(x,p));if(i<0){S.pairs.unshift(p);i=0}select(i);const drv=marketDrivers(p),rn=relevantNews(p);showDetail('SCHEDA TOKEN',`${p.baseToken?.name} (${p.baseToken?.symbol})`,`<div class="detail-grid"><div class="detail-block"><span>Prezzo</span><b>${usd(p.priceUsd,8)}</b></div><div class="detail-block"><span>24h</span><b class="${num(p.priceChange?.h24)>=0?'up':'down'}">${num(p.priceChange?.h24)>=0?'+':''}${fmt(p.priceChange?.h24,2)}%</b></div><div class="detail-block"><span>Liquidità</span><b>${short(p.liquidity?.usd)}</b></div><div class="detail-block"><span>Volume</span><b>${short(p.volume?.h24)}</b></div><div class="detail-block"><span>Settore</span><b>${sector(p)}</b></div><div class="detail-block"><span>Rischio</span><b>${risk(p)}/100</b></div></div><div class="detail-section"><h3>Cosa ci dicono i dati</h3><div class="detail-list">${drv.map(x=>`<div class="detail-row"><div><b>${esc(x.title)}</b><div class="small">${esc(x.text)}</div></div></div>`).join('')}</div></div><div class="detail-section"><h3>News pertinenti</h3><div class="detail-list">${rn.map(n=>`<div class="detail-row"><div><b>${esc(n.title)}</b><div class="small">Perché conta: ${esc(n.why||'Da verificare.')}</div></div><span class="v14-chip">${esc(n.impact||'')}</span></div>`).join('')||'<div class="small">Nessuna news diretta nel feed corrente.</div>'}</div></div><div class="row-actions top-gap"><button class="btn primary" id="goLab">Apri Laboratorio completo</button><button class="btn" id="addFromDetail">Aggiungi/aggiorna osservazione</button></div>`);$('goLab').onclick=()=>{closeDetail();document.querySelector('.lab')?.scrollIntoView({behavior:'smooth',block:'start'})};$('addFromDetail').onclick=()=>{v13AddWatch();renderHub();$('addFromDetail').textContent='Dati aggiornati'} }
applyFilters=function(){V14_applyFilters();qa('#rows tr[data-i]').forEach(r=>r.onclick=()=>openTokenObject(S.pairs[+r.dataset.i]));};
async function loadV14Market(){try{const d=await v14api('market'),seen=[];S.pairs=(d.pairs||[]).filter(p=>{if(seen.some(x=>sameToken(x,p)))return false;seen.push(p);return true});applyFilters();renderSectors();$('liveStatus').textContent='V14 INTELLIGENCE LIVE'}catch(e){v13Market()}}
async function loadNewProjects(){try{const d=await v14api('new');S.newProjects=d.pairs||[];renderNewProjects()}catch(e){$('newProjectsGrid').innerHTML='<div class="small">Feed nuovi progetti temporaneamente non disponibile.</div>'}}
function renderNewProjects(){const a=S.newProjects.slice(0,12);$('newProjectsGrid').innerHTML=a.length?a.map((p,i)=>`<div class="new-card"><h4>${esc(p.baseToken?.symbol)} · ${esc(p.baseToken?.name)}</h4><div class="small">${ageText(p.createdAt)} · ${esc(p.dexId||'DEX')}</div><div class="meta-row"><span>Prezzo ${usd(p.priceUsd,8)}</span><span class="${num(p.priceChange?.h24)>=0?'up':'down'}">${num(p.priceChange?.h24)>=0?'+':''}${fmt(p.priceChange?.h24,2)}%</span></div><div class="meta-row"><span>Liq ${short(p.liquidity?.usd)}</span><span>Vol ${short(p.volume?.h24)}</span><span>Rischio ${risk(p)}/100</span></div><button class="btn new-open" data-new="${i}">Analizza progetto</button></div>`).join(''):'<div class="small">Nessun nuovo pool nel feed corrente.</div>';qa('.new-open').forEach(b=>b.onclick=()=>openTokenObject(a[+b.dataset.new]))}
function updateFlash(){const n=S.news?.[0];if(!n)return;$('flashTitle').innerHTML=n.url?`<a href="${esc(n.url)}" target="_blank" rel="noopener">${esc(n.title)}</a>`:esc(n.title);$('flashSource').textContent=n.source||'Fonte';$('flashTime').textContent=n.published?new Date(n.published).toLocaleString('it-IT'):'Ora non disponibile';$('flashImpact').textContent=`${n.impact||'Impatto'} ${n.impactScore||''}`;$('flashImpact').className='v14-chip '+(num(n.impactScore)>=70?'down':num(n.impactScore)>=45?'':'up');$('flashWhy').textContent='Perché conta: '+(n.why||'Da contestualizzare con i dati di mercato.');if($('newsSources'))$('newsSources').textContent=`Fonti attive: ${S.newsMeta?.sources?.length||new Set(S.news.map(x=>x.source)).size}`}
loadNews=async function(){try{const d=await v14api('news');S.news=d.items||[];S.newsMeta=d;renderNews(document.querySelector('.tab.active')?.dataset.filter||'all');newsNotif(S.news);updateFlash();buildIntel();if(S.selected)buildIntel()}catch(e){$('newsList').innerHTML='<div class="small">News temporaneamente non disponibili.</div>'}};
function std(a){if(a.length<2)return 0;const m=a.reduce((x,y)=>x+y,0)/a.length;return Math.sqrt(a.reduce((x,y)=>x+(y-m)*(y-m),0)/(a.length-1))}
function graphExplain(cl,period){const first=cl[0],last=cl.at(-1),lo=Math.min(...cl),hi=Math.max(...cl),change=(last-first)/first*100,rets=cl.slice(1).map((x,i)=>(x/cl[i]-1)*100),vol=std(rets),range=(hi-lo)/lo*100;let peak=cl[0],dd=0;for(const x of cl){peak=Math.max(peak,x);dd=Math.min(dd,(x/peak-1)*100)}const pos=(hi-lo)?(last-lo)/(hi-lo)*100:50,dir=change>5?'Rialzo':change<-5?'Ribasso':'Laterale / misto';$('giDirection').textContent=`${dir} ${change>=0?'+':''}${fmt(change,2)}%`;$('giLow').textContent=usd(lo,8);$('giHigh').textContent=usd(hi,8);$('giVol').textContent=fmt(vol,2)+'%';$('giDD').textContent=fmt(dd,2)+'%';$('graphStory').textContent=`Nel periodo ${period.toUpperCase()} il prezzo è ${change>=0?'salito':'sceso'} del ${fmt(Math.abs(change),2)}%. Range osservato ${fmt(range,2)}%; il prezzo attuale si trova circa al ${fmt(pos,0)}% del range tra minimo e massimo. Volatilità media tra punti ${fmt(vol,2)}% e massimo drawdown ${fmt(dd,2)}%. Questi numeri descrivono il movimento, non prevedono quello successivo.`}
loadHistory=async function(period){if(!S.selected)return;S.period=period;qa('.time').forEach(b=>b.classList.toggle('active',b.dataset.period===period));$('historyHint').textContent='Caricamento storico...';try{const d=await v14api('history',{pool:S.selected.pairAddress,period}),a=(d.ohlcv||[]).slice().reverse(),cl=a.map(x=>+x[4]).filter(Number.isFinite);if(!cl.length)throw Error();draw('historyLine',cl);const ch=(cl.at(-1)-cl[0])/cl[0]*100;$('historyHint').textContent=`${period.toUpperCase()} · ${cl.length} punti · ${d.source||'storico'}`;$('periodStats').textContent=`${ch>=0?'+':''}${fmt(ch,2)}% · ${usd(cl[0],8)} → ${usd(cl.at(-1),8)}`;graphExplain(cl,period);buildIntel()}catch(e){$('historyHint').textContent='Storico non disponibile per questo pool/periodo.';$('periodStats').textContent='—';$('graphStory').textContent='Non ci sono abbastanza dati storici per descrivere questo intervallo.'}};
renderWatch=function(){V14_renderWatch();renderHub()};
function renderHub(){if(!$('hubList'))return;const w=S.watch||[],up=w.filter(x=>num(x.change24)>0).length,down=w.filter(x=>num(x.change24)<0).length,high=w.filter(x=>num(x.risk)>=60).length,secs=new Set(w.map(x=>x.sector).filter(Boolean));$('hubTotal').textContent=w.length;$('hubUp').textContent=up;$('hubDown').textContent=down;$('hubHighRisk').textContent=high;$('hubSectors').textContent=secs.size;$('hubUpdated').textContent='Aggiornato '+new Date().toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'});let a=w;if(S.hubFilter==='up')a=w.filter(x=>num(x.change24)>0);if(S.hubFilter==='down')a=w.filter(x=>num(x.change24)<0);if(S.hubFilter==='risk')a=w.filter(x=>num(x.risk)>=60);a=[...a].sort((x,y)=>Math.abs(num(y.change24))-Math.abs(num(x.change24)));$('hubList').innerHTML=a.length?a.map((x,i)=>{const width=Math.min(100,Math.max(5,Math.abs(num(x.change24))*5));return`<div class="hub-token"><h4>${esc(x.symbol)} · ${esc(x.sector||'Altro')}</h4><div>${usd(x.price,8)} · <b class="${num(x.change24)>=0?'up':'down'}">${num(x.change24)>=0?'+':''}${fmt(x.change24,2)}%</b></div><div class="trendline"><i style="width:${width}%"></i></div><div class="small">Rischio ${x.risk}/100 · Liq ${short(x.liq)} · Vol ${short(x.vol)}</div><div class="token-actions"><button class="btn hub-open" data-key="${esc(x.key||x.address||x.symbol)}">Apri</button></div></div>`}).join(''):'<div class="small">Nessun token in questo filtro.</div>';qa('.hub-open').forEach(b=>b.onclick=async()=>{const x=w.find(z=>String(z.key||z.address||z.symbol)===b.dataset.key);if(!x)return;const q=x.address||x.symbol;try{const d=await v14api('search',{q});const p=(d.pairs||[]).find(p=>sameToken(x,p))||(d.pairs||[])[0];if(p)openTokenObject(p)}catch{}})}
function v14Bind(){v14Inject();loadV14Market();loadNewProjects();loadNews();renderHub();renderSectors();$('refreshMarket').onclick=loadV14Market;$('refreshNews').onclick=loadNews;$('refreshWatch').onclick=async()=>{await refreshWatch();renderHub()};bindSectorButtons();setInterval(()=>{const s=$('liveStatus');if(s)s.textContent='V14 INTELLIGENCE LIVE'},5000);setInterval(loadNews,180000);setInterval(loadV14Market,300000);setInterval(()=>{refreshWatch();renderHub()},120000)}
v14Bind();
