(()=>{
const q=id=>document.getElementById(id), one=s=>document.querySelector(s), all=s=>[...document.querySelectorAll(s)];
const shortText=(t,n=120)=>{t=String(t||'').replace(/\s+/g,' ').trim();return t.length>n?t.slice(0,n-1)+'…':t};
const fmtN=(v,d=1)=>{v=Number(v);return Number.isFinite(v)?v.toFixed(d):'—'};
const cards={};
function wrapCard(card,key,title,sub,previewFn,open=false){if(!card||card.dataset.v16)return;card.dataset.v16=key;card.classList.add('v16-collapsible');const content=document.createElement('div');content.className='v16-content';while(card.firstChild)content.appendChild(card.firstChild);const head=document.createElement('button');head.type='button';head.className='v16-compact-head';head.innerHTML=`<div class="v16-head-main"><div class="v16-head-title">${title}</div><div class="v16-head-sub">${sub}</div><div class="v16-head-preview" data-v16-preview="${key}">Apri per vedere i dettagli.</div></div><div class="v16-chevron">⌄</div>`;card.appendChild(head);card.appendChild(content);cards[key]={card,head,content,previewFn};if(open)card.classList.add('open');head.onclick=()=>toggle(key);}
function toggle(key,force){const x=cards[key];if(!x)return;const will=force==null?!x.card.classList.contains('open'):force;if(will){Object.entries(cards).forEach(([k,v])=>{if(k!==key)v.card.classList.remove('open')});x.card.classList.add('open');setTimeout(()=>x.card.scrollIntoView({behavior:'smooth',block:'start'}),60)}else x.card.classList.remove('open');refreshPreviews()}
function addMenu(){if(q('v16Menu'))return;const anchor=q('v15Home')||one('.hero');if(!anchor)return;const m=document.createElement('nav');m.id='v16Menu';m.className='v16-menu';const defs=[['market','Mercato','Cerca e filtra token'],['lab','Analisi','Apri il token nel laboratorio'],['watch','Monitorati','La tua lista osservazione'],['news','Notizie','Ultime notizie e perché contano'],['sectors','Settori','Vedi quali comparti salgono o scendono'],['macro','Macro','Dollaro e contesto globale'],['sec','SEC & Regole','Comunicati ufficiali'],['new','Nuovi progetti','Nuovi pool BNB Chain']];m.innerHTML=defs.map(d=>`<button class="v16-nav" data-open="${d[0]}"><b>${d[1]}</b><span>${d[2]}</span><i class="v16-count" data-v16-count="${d[0]}">Apri</i></button>`).join('');anchor.insertAdjacentElement('afterend',m);all('.v16-nav').forEach(b=>b.onclick=()=>toggle(b.dataset.open,true));}
function rewrite(){const hp=one('.hero p');if(hp)hp.textContent='Segui BNB, token, settori e notizie. Apri solo la sezione che ti serve.';const vh=q('v15Home');if(vh){const h=vh.querySelector('h2');if(h)h.textContent='Cosa conta adesso';const s=vh.querySelector('.head .small');if(s)s.textContent='I segnali principali, senza rumore.'}
const map=[[q('newsList')?.closest('.card'),'Notizie','Cosa può influenzare mercato e token'],[q('sectorList')?.closest('.card'),'Settori','Dove si sta muovendo il mercato'],[q('dxyValue')?.closest('.card'),'Dollaro & Macro','Contesto globale'],[q('secList')?.closest('.card'),'SEC & Regole','Comunicati ufficiali'],[one('.lab'),'Analisi Token','Dati, motivi, rischi e notizie'],[q('watchCards')?.closest('.card'),'Token monitorati','La tua lista osservazione'],[q('rows')?.closest('.card'),'Mercato Token','Cerca, filtra e apri un progetto'],[q('newProjectsCard'),'Nuovi progetti','Nuovi pool rilevati sulla BNB Chain']];for(const [c,t,s] of map){if(!c)continue;const h=c.querySelector('.head h2');if(h)h.textContent=t;const sm=c.querySelector('.head .small');if(sm)sm.textContent=s}}
function build(){rewrite();addMenu();wrapCard(q('rows')?.closest('.card'),'market','Mercato Token','Cerca e filtra i progetti',()=>`${q('count')?.textContent||'Mercato in aggiornamento'}`,true);wrapCard(one('.lab'),'lab','Analisi Token','Apri un token e leggi solo ciò che conta',()=>{const n=q('labName')?.textContent;return n&& !/nessun/i.test(n)?`${n} · ${q('drisk')?.textContent||''}`:'Nessun token selezionato.'});wrapCard(q('watchCards')?.closest('.card'),'watch','Token monitorati','La tua lista osservazione',()=>{const n=q('watchCount')?.textContent||'0',a=q('watchAvg')?.textContent||'—';return `${n} token · media 24h ${a}`});wrapCard(q('newsList')?.closest('.card'),'news','Notizie','Una notizia in evidenza, tutte le altre dentro',latestNews);wrapCard(q('sectorList')?.closest('.card'),'sectors','Settori','Cosa sono e come si stanno muovendo',sectorPreview);wrapCard(q('dxyValue')?.closest('.card'),'macro','Dollaro & Macro','Contesto globale',()=>`USD Strength ${q('dxyValue')?.textContent||'—'} · USD/EUR ${q('usdEur')?.textContent||'—'}`);wrapCard(q('secList')?.closest('.card'),'sec','SEC & Regole','Fonte ufficiale e impatto',()=>`${(window.S?.sec||[]).length||0} comunicati caricati`);wrapCard(q('newProjectsCard'),'new','Nuovi progetti','Nuovi pool da controllare',()=>`${(window.S?.newProjects||[]).length||0} progetti nel feed`);if(q('compareCenter'))wrapCard(q('compareCenter'),'compare','Confronto Token','Confronta due token solo quando serve',()=>`${(window.S?.watch||[]).length||0} token disponibili`);if(q('labHub'))wrapCard(q('labHub'),'hub','Laboratorio Centrale','Up, down e rischio della lista',()=>hubPreview());refreshPreviews();observe();badge();}
function latestNews(){const a=window.S?.news||[];if(!a.length)return'Notizie in aggiornamento.';const n=[...a].sort((x,y)=>new Date(y.published||0)-new Date(x.published||0))[0];return `${shortText(n.title,105)} · ${n.source||'Fonte'}`}
function sectorPreview(){const pairs=window.S?.pairs||[];if(!pairs.length)return'Settori in aggiornamento.';const g={};pairs.forEach(p=>{const s=typeof sector==='function'?sector(p):'Altro';(g[s]??=[]).push(Number(p.priceChange?.h24)||0)});const arr=Object.entries(g).map(([s,v])=>[s,v.reduce((a,b)=>a+b,0)/v.length]).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1]));return arr[0]?`${arr[0][0]} ${arr[0][1]>=0?'↑':'↓'} ${fmtN(Math.abs(arr[0][1]),2)}% · ${Object.keys(g).length} settori`:'Nessun dato settore.'}
function hubPreview(){const w=window.S?.watch||[];const up=w.filter(x=>(Number(x.change24)||0)>0).length,down=w.filter(x=>(Number(x.change24)||0)<0).length;return `${w.length} token · Up ${up} / Down ${down}`}
function refreshPreviews(){Object.entries(cards).forEach(([k,x])=>{const el=document.querySelector(`[data-v16-preview="${k}"]`);if(el&&x.previewFn){try{el.textContent=x.previewFn()}catch{}}});const counts={market:q('count')?.textContent||'Apri',lab:q('labStatus')?.textContent||'Apri',watch:`${q('watchCount')?.textContent||0} token`,news:`${(window.S?.news||[]).length} news`,sectors:`${new Set((window.S?.pairs||[]).map(p=>typeof sector==='function'?sector(p):'Altro')).size} settori`,macro:q('dxyValue')?.textContent||'Apri',sec:`${(window.S?.sec||[]).length} voci`,new:`${(window.S?.newProjects||[]).length} nuovi`};Object.entries(counts).forEach(([k,v])=>{const el=document.querySelector(`[data-v16-count="${k}"]`);if(el)el.textContent=v});badge()}
function badge(){const el=q('liveStatus');if(el)el.textContent='V16 LIVE · INTERFACCIA SEMPLICE';document.title='Kibernetic BNB Intelligence V16';const e=one('.hero .eyebrow');if(e)e.textContent='BNB CHAIN INTELLIGENCE · V16'}
function observe(){const obs=new MutationObserver(()=>refreshPreviews());['newsList','watchCards','sectorOutput','newProjectsGrid','labName','dxyValue','secList','rows'].forEach(id=>{const e=q(id);if(e)obs.observe(e,{childList:true,subtree:true,characterData:true})});setInterval(refreshPreviews,5000)}
function boot(){setTimeout(build,950);setTimeout(()=>{refreshPreviews();badge()},2200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
