const RESEARCH='https://iytjxruxpvwjjhbndkzo.supabase.co/functions/v1/kibernetic-research';
const V18={point:null,locked:false,memory:[],pointResearch:null,dossier:JSON.parse(localStorage.getItem('kiber_v18_dossier')||'{"news":[],"tokens":[]}')};
state.dossier=V18.dossier;

function v18PeriodHours(period){return ({'24h':24,'7d':168,'1m':720,'1y':2160,'3y':2160})[period]||168}
function v18ResearchWindow(period){return ({'24h':3,'7d':12,'1m':24,'1y':72,'3y':168})[period]||12}
function v18Date(ts){return new Date(ts).toLocaleString('it-IT',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function v18NearestSnapshot(ts){if(!V18.memory.length)return null;let best=null,dist=Infinity;for(const x of V18.memory){const d=Math.abs(new Date(x.captured_at).getTime()-ts);if(d<dist){best=x;dist=d}}const max=state.period==='24h'?3*3600000:state.period==='7d'?8*3600000:36*3600000;return dist<=max?best:null}

function v18EnsureChart(){const svg=$('priceChart');if(!svg)return;svg.classList.add('interactive-chart');if(!svg.querySelector('#v18Gradient')){const NS='http://www.w3.org/2000/svg';const defs=document.createElementNS(NS,'defs'),grad=document.createElementNS(NS,'linearGradient');grad.id='v18Gradient';grad.setAttribute('x1','0');grad.setAttribute('y1','0');grad.setAttribute('x2','0');grad.setAttribute('y2','1');const s1=document.createElementNS(NS,'stop'),s2=document.createElementNS(NS,'stop');s1.setAttribute('offset','0%');s1.setAttribute('stop-color','var(--accent)');s1.setAttribute('stop-opacity','.30');s2.setAttribute('offset','100%');s2.setAttribute('stop-color','var(--accent)');s2.setAttribute('stop-opacity','0');grad.append(s1,s2);defs.appendChild(grad);svg.prepend(defs);const area=document.createElementNS(NS,'polygon');area.id='priceArea';area.setAttribute('fill','url(#v18Gradient)');svg.insertBefore(area,$('priceLine'));const vg=document.createElementNS(NS,'g');vg.id='volumeBars';svg.insertBefore(vg,$('priceLine'));const line=document.createElementNS(NS,'line');line.id='chartCursorLine';line.setAttribute('y1','20');line.setAttribute('y2','260');line.setAttribute('class','chart-cursor-line');line.style.display='none';svg.appendChild(line);const dot=document.createElementNS(NS,'circle');dot.id='chartCursorDot';dot.setAttribute('r','7');dot.setAttribute('class','chart-cursor-dot');dot.style.display='none';svg.appendChild(dot)}
const card=svg.closest('.chart-card');if(card&&!$('pointInspector')){const box=document.createElement('div');box.id='pointInspector';box.className='point-inspector';box.innerHTML='<div><span>PUNTO SELEZIONATO</span><b id="pointWhen">Muovi il dito sul grafico</b><small id="pointLock">Tocca un punto per bloccarlo</small></div><div class="point-metrics"><div><span>Prezzo</span><b id="pointPrice">—</b></div><div><span>Volume candela</span><b id="pointVolume">—</b></div><div><span>Liquidità storica</span><b id="pointLiquidity">—</b></div><div><span>O / H / L</span><b id="pointOhl">—</b></div></div><div class="point-actions"><button class="primary" id="analyzePointBtn" disabled>Analizza questo punto</button><button class="secondary" id="askPointKiber" disabled>Chiedi a Kiber</button></div><div id="pointAnalysis" class="point-analysis" hidden></div>';svg.insertAdjacentElement('afterend',box);$('analyzePointBtn').onclick=analyzePoint;$('askPointKiber').onclick=askPointKiber}
if(!svg.dataset.v18Bound){svg.dataset.v18Bound='1';svg.addEventListener('pointermove',e=>{if(!V18.locked)v18PickPoint(e)});svg.addEventListener('click',e=>{V18.locked=!V18.locked;v18PickPoint(e);$('pointLock').textContent=V18.locked?'Punto bloccato · tocca di nuovo per sbloccare':'Tocca un punto per bloccarlo'});svg.addEventListener('pointerleave',()=>{if(!V18.locked){$('chartCursorLine').style.display='none';$('chartCursorDot').style.display='none'}})}}

function v18PickPoint(e){const a=state.history||[];if(!a.length)return;const svg=$('priceChart'),r=svg.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),i=Math.round(ratio*(a.length-1));v18ShowPoint(i)}
function v18ShowPoint(i){const a=state.history||[],row=a[i];if(!row)return;const ts=N(row[0])*1000,open=N(row[1]),high=N(row[2]),low=N(row[3]),close=N(row[4]),vol=N(row[5]),snap=v18NearestSnapshot(ts),lo=Math.min(...a.map(x=>N(x[4])).filter(x=>x>0)),hi=Math.max(...a.map(x=>N(x[4])).filter(x=>x>0)),range=hi-lo||1,x=40+i/(a.length-1)*740,y=245-(close-lo)/range*200;V18.point={i,ts,open,high,low,close,volume:vol,snapshot:snap};const line=$('chartCursorLine'),dot=$('chartCursorDot');line.setAttribute('x1',x);line.setAttribute('x2',x);line.style.display='';dot.setAttribute('cx',x);dot.setAttribute('cy',y);dot.style.display='';$('pointWhen').textContent=v18Date(ts);$('pointPrice').textContent=usd(close,8);$('pointVolume').textContent=short(vol);$('pointLiquidity').textContent=snap?short(snap.liquidity_usd):'non disponibile';$('pointOhl').textContent=`${usd(open,5)} / ${usd(high,5)} / ${usd(low,5)}`;$('analyzePointBtn').disabled=false;$('askPointKiber').disabled=false}

loadHistory=async function(period){const t=state.selected;if(!t?.pairs?.[0]?.pairAddress)return;state.period=period;$$('.periods button').forEach(b=>b.classList.toggle('active',b.dataset.period===period));$('chartStory').textContent='Caricamento storico e memoria…';V18.locked=false;V18.point=null;V18.pointResearch=null;try{const [d,m]=await Promise.all([j(DATA+'?type=history&pool='+encodeURIComponent(t.pairs[0].pairAddress)+'&period='+period),j(MEM+'?type=history&addresses='+encodeURIComponent(t.address)+'&hours='+v18PeriodHours(period)).catch(()=>({items:[]}))]),a=(d.ohlcv||[]).slice().reverse();state.history=a;V18.memory=(m.items||[]).filter(x=>String(x.token_address).toLowerCase()===String(t.address).toLowerCase());drawHistory(a,period)}catch{$('chartStory').textContent='Storico non disponibile per questo pool o periodo.'}}

drawHistory=function(a,period){const close=a.map(x=>N(x[4])).filter(x=>x>0);if(close.length<2){$('chartStory').textContent='Pochi dati per questo periodo.';return}v18EnsureChart();const lo=Math.min(...close),hi=Math.max(...close),range=hi-lo||1,coords=close.map((x,i)=>[40+i/(close.length-1)*740,245-(x-lo)/range*200]);$('priceLine').setAttribute('points',coords.map(x=>x.join(',')).join(' '));$('priceArea').setAttribute('points',`${coords.map(x=>x.join(',')).join(' ')} 780,260 40,260`);$('chartMax').textContent=usd(hi,6);$('chartMin').textContent=usd(lo,6);const vg=$('volumeBars');vg.innerHTML='';const vols=a.map(x=>Math.max(0,N(x[5]))),vmax=Math.max(...vols,1),NS='http://www.w3.org/2000/svg';vols.forEach((v,i)=>{const rect=document.createElementNS(NS,'rect'),w=Math.max(2,720/vols.length*.62),x=40+i/(vols.length-1)*740-w/2,h=v/vmax*34;rect.setAttribute('x',x);rect.setAttribute('y',260-h);rect.setAttribute('width',w);rect.setAttribute('height',h);rect.setAttribute('class','volume-bar');vg.appendChild(rect)});const move=(close.at(-1)/close[0]-1)*100,rets=close.slice(1).map((x,i)=>x/close[i]-1),mean=rets.reduce((z,x)=>z+x,0)/(rets.length||1),vol=Math.sqrt(rets.reduce((z,x)=>z+(x-mean)**2,0)/(rets.length||1))*100;let peak=close[0],dd=0;for(const x of close){peak=Math.max(peak,x);dd=Math.min(dd,(x/peak-1)*100)}$('chartMove').textContent=(move>=0?'+':'')+fmt(move,2)+'%';$('chartMove').className=move>=0?'up':'down';$('chartRange').textContent=`${period.toUpperCase()} · ${close.length} punti · cursore attivo`;$('gDirection').textContent=Math.abs(move)<2?'Laterale':move>0?'Rialzo':'Ribasso';$('gVolatility').textContent=fmt(vol,2)+'%';$('gDrawdown').textContent=fmt(dd,2)+'%';$('gPoints').textContent=close.length;$('chartStory').textContent=`Nel periodo il prezzo è ${move>=0?'salito':'sceso'} del ${fmt(Math.abs(move),2)}%. Tocca o trascina sul grafico per vedere data, prezzo, volume e liquidità storica quando disponibile; poi usa “Analizza questo punto” per cercare cosa accadeva in quel momento.`;v18ShowPoint(close.length-1)}

async function analyzePoint(){const p=V18.point,t=state.selected;if(!p||!t)return;const box=$('pointAnalysis');box.hidden=false;box.innerHTML='<div class="research-loading">Ricerca su più fonti in corso…</div>';try{const u=RESEARCH+'?type=event&name='+encodeURIComponent(t.name||'')+'&symbol='+encodeURIComponent(t.symbol||'')+'&address='+encodeURIComponent(t.address||'')+'&timestamp='+encodeURIComponent(new Date(p.ts).toISOString())+'&hours='+v18ResearchWindow(state.period)+'&price='+encodeURIComponent(p.close)+'&volume='+encodeURIComponent(p.volume)+'&liquidity='+encodeURIComponent(p.snapshot?.liquidity_usd||'');const d=await j(u);V18.pointResearch=d;renderPointResearch(d)}catch{box.innerHTML='<div class="muted">Ricerca del contesto non disponibile in questo momento.</div>'}}
function renderPointResearch(d){const box=$('pointAnalysis'),f=(d.factors||[]).slice(0,5),arts=(d.articles||[]).slice(0,8);box.innerHTML=`<div class="research-head"><div><span>ANALISI DEL PUNTO</span><b>${esc(d.conclusion||'')}</b></div><strong>Confidenza ${Math.round(N(d.confidence)*100)}%</strong></div><div class="research-factors">${f.map(x=>`<span>${esc(x.label)} · ${x.count}</span>`).join('')||'<span>Nessun fattore forte trovato</span>'}</div><div class="engine-line">Fonti/motori: ${esc((d.engines||[]).join(' · ')||'—')}</div><div class="research-results">${arts.map(x=>`<a href="${esc(x.url||'#')}" target="_blank" rel="noopener"><b>${esc(x.title)}</b><small>${esc(x.source||x.sources?.join(', ')||'Fonte')} · ${x.published?v18Date(new Date(x.published).getTime()):'data n/d'} · ${esc(x.factor||'')}</small></a>`).join('')||'<div class="muted">Nessuna notizia sufficientemente pertinente nell’intervallo.</div>'}</div><p class="research-note">Le fonti indicano possibili influenze. La vicinanza temporale tra notizia e movimento non dimostra da sola che la notizia abbia causato il prezzo.</p>`}
function askPointKiber(){if(!V18.point||!state.selected)return;const r=V18.pointResearch,ctx=r?` Ricerca: ${r.conclusion} Fattori: ${(r.factors||[]).slice(0,3).map(x=>x.label+' '+x.count).join(', ')}.`:'';openSection('kiber');sendChat(`Analizza ${state.selected.symbol} nel punto del ${v18Date(V18.point.ts)}: prezzo ${usd(V18.point.close,8)}, volume ${short(V18.point.volume)}, liquidità storica ${V18.point.snapshot?short(V18.point.snapshot.liquidity_usd):'non disponibile'}.${ctx} Spiegami fatti, possibili motivazioni, dati contrari e cosa controllare.`)}

function v18NewsKey(n){return String(n.cluster_key||n.id||norm(n.title).slice(0,90)).toLowerCase().replace(/[^a-z0-9:_-]/g,'_')}
function v18SaveDossier(){localStorage.setItem('kiber_v18_dossier',JSON.stringify(V18.dossier));state.dossier=V18.dossier;renderDossier();syncNewsWatch()}
async function syncNewsWatch(){try{await cloud('newswatch',{method:'POST',body:JSON.stringify({items:V18.dossier.news.map(n=>({topicKey:v18NewsKey(n),title:n.title,query:n.query||n.title,tokenAddresses:n.tokenAddresses||[],enabled:true}))})})}catch{}}
function addNewsToMonitor(i,withToken=false){const n=state.news[i];if(!n)return;if(!V18.dossier.news.some(x=>v18NewsKey(x)===v18NewsKey(n)))V18.dossier.news.push({id:n.id,cluster_key:n.cluster_key,title:n.title,query:n.title,source:n.sources?.[0]?.name||n.source||'Fonte',published:n.published_at||n.published,url:n.primary_url||n.url||'',why:n.why_it_matters||n.why||'',tokenAddresses:n.token_addresses||[]});if(withToken&&state.selected&&!V18.dossier.tokens.some(x=>x.address?.toLowerCase()===state.selected.address?.toLowerCase()))V18.dossier.tokens.push({address:state.selected.address,symbol:state.selected.symbol,name:state.selected.name,sector:state.selected.sector});v18SaveDossier();ensureDossierPanel();openSection('dossier');if(withToken)analyzeDossier()}
function toggleDossierToken(address){const w=state.watch.find(x=>x.address?.toLowerCase()===address.toLowerCase());if(!w)return;const i=V18.dossier.tokens.findIndex(x=>x.address?.toLowerCase()===address.toLowerCase());if(i>=0)V18.dossier.tokens.splice(i,1);else V18.dossier.tokens.push({address:w.address,symbol:w.symbol,name:w.name,sector:w.sector});v18SaveDossier()}
function removeDossierNews(key){V18.dossier.news=V18.dossier.news.filter(x=>v18NewsKey(x)!==key);v18SaveDossier()}

function ensureDossierPanel(){if($('section-dossier'))return;const nav=document.createElement('button');nav.dataset.section='dossier';nav.innerHTML='<b>Dossier</b><span id="dossierCountNav">0 elementi</span>';nav.onclick=()=>openSection('dossier');$('hubNav').appendChild(nav);const sec=document.createElement('section');sec.className='panel';sec.id='section-dossier';sec.innerHTML='<button class="section-head"><div><h2>Dossier Ricerca</h2><p>Mescola più notizie e più token, poi cerca connessioni e dati contrari.</p></div><span>⌄</span></button><div class="section-body"><div class="dossier-columns"><div><h3>Notizie monitorate</h3><div id="dossierNews" class="stack"></div></div><div><h3>Token da confrontare</h3><div id="dossierTokens" class="chip-list"></div><h4>Aggiungi dai monitorati</h4><div id="dossierWatchChoices" class="chip-list"></div></div></div><button class="primary" id="runDossier">Analizza insieme</button><div id="dossierOutput" class="dossier-output"></div></div>';const k=$('section-kiber');k.parentNode.insertBefore(sec,k);sec.querySelector('.section-head').onclick=()=>sec.classList.toggle('open');$('runDossier').onclick=analyzeDossier;renderDossier()}
function renderDossier(){if(!$('section-dossier'))return;$('dossierCountNav').textContent=(V18.dossier.news.length+V18.dossier.tokens.length)+' elementi';$('dossierNews').innerHTML=V18.dossier.news.length?V18.dossier.news.map(n=>`<div><b>${esc(n.title)}</b><small>${esc(n.source||'Fonte')}</small><button class="tiny" data-rm-news="${esc(v18NewsKey(n))}">Rimuovi</button></div>`).join(''):'<div class="muted">Nessuna notizia monitorata.</div>';$('dossierTokens').innerHTML=V18.dossier.tokens.length?V18.dossier.tokens.map(t=>`<button class="chip active" data-dossier-token="${esc(t.address)}">${esc(t.symbol||t.name)} ×</button>`).join(''):'<span class="muted">Nessun token scelto.</span>';$('dossierWatchChoices').innerHTML=state.watch.length?state.watch.map(t=>`<button class="chip ${V18.dossier.tokens.some(x=>x.address?.toLowerCase()===t.address?.toLowerCase())?'active':''}" data-dossier-token="${esc(t.address)}">${esc(t.symbol||t.name)}</button>`).join(''):'<span class="muted">Aggiungi prima dei token ai monitorati.</span>';$$('[data-rm-news]').forEach(b=>b.onclick=()=>removeDossierNews(b.dataset.rmNews));$$('[data-dossier-token]').forEach(b=>b.onclick=()=>toggleDossierToken(b.dataset.dossierToken))}
async function analyzeDossier(){ensureDossierPanel();const out=$('dossierOutput');out.innerHTML='<div class="research-loading">Ricerca incrociata su più fonti…</div>';try{const d=await j(RESEARCH+'?type=dossier',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tokens:V18.dossier.tokens,news:V18.dossier.news})});out.innerHTML=`<div class="research-head"><div><span>DOSSIER</span><b>${esc(d.conclusion||'')}</b></div><strong>Confidenza ${Math.round(N(d.confidence)*100)}%</strong></div><div class="research-factors">${(d.themes||[]).slice(0,6).map(x=>`<span>${esc(x.label)} · ${x.count}</span>`).join('')}</div><div class="engine-line">Motori: ${esc((d.engines||[]).join(' · ')||'—')}</div><div class="research-results">${(d.articles||[]).slice(0,10).map(x=>`<a href="${esc(x.url||'#')}" target="_blank" rel="noopener"><b>${esc(x.title)}</b><small>${esc(x.source||x.sources?.join(', ')||'Fonte')}</small></a>`).join('')}</div>`}catch{out.innerHTML='<div class="muted">Analisi dossier non disponibile.</div>'}}

renderNews=function(){const f=state.newsFilter,a=state.news.filter(n=>f==='all'||newsCat(n)===f);$('newsList').innerHTML=a.length?a.map(n=>{const i=state.news.indexOf(n),score=N(n.impact_score||n.impactScore),label=n.impact_label||n.impact||(score>=80?'Alto':score>=60?'Medio':'Basso'),src=n.sources?.[0]?.name||n.source||'Fonte',mon=V18.dossier.news.some(x=>v18NewsKey(x)===v18NewsKey(n));return`<article class="news-item"><div data-open-news="${i}"><h3>${esc(n.title)}</h3><div class="news-meta"><span>${esc(src)}</span><span>${age(n.published_at||n.published)}</span><span>${esc(newsCat(n))}</span><span class="impact ${score>=80?'down':score>=60?'warn':''}">Impatto ${esc(label)}</span>${n.source_count?`<span>${n.source_count} fonti</span>`:''}</div><div class="why">Perché conta: ${esc(n.why_it_matters||n.why||'Da confrontare con i dati di mercato.')}</div></div><div class="news-actions"><button class="secondary mini" data-monitor-news="${i}">${mon?'Monitorata ✓':'Monitora'}</button><button class="primary mini" data-analyze-news="${i}">Analizza + token</button></div></article>`}).join(''):'<div class="muted">Nessuna notizia in questa categoria.</div>';$$('[data-open-news]').forEach(x=>x.onclick=()=>openNews(Number(x.dataset.openNews)));$$('[data-monitor-news]').forEach(x=>x.onclick=e=>{e.stopPropagation();addNewsToMonitor(Number(x.dataset.monitorNews),false);renderNews()});$$('[data-analyze-news]').forEach(x=>x.onclick=e=>{e.stopPropagation();addNewsToMonitor(Number(x.dataset.analyzeNews),true)})}
renderTokenNews=function(){const t=state.selected;if(!t)return;const s=(t.symbol||'').toLowerCase(),n=(t.name||'').toLowerCase(),a=state.news.filter(x=>(x.token_addresses||[]).map(z=>z.toLowerCase()).includes(t.address.toLowerCase())||String(x.title||'').toLowerCase().includes(n)||(s.length>=3&&new RegExp(`\\b${s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'i').test(x.title||''))).slice(0,12);$('tokenNewsList').innerHTML=a.length?a.map(x=>{const i=state.news.indexOf(x);return`<article class="news-item"><h3>${esc(x.title)}</h3><div class="news-meta"><span>${esc(x.sources?.[0]?.name||x.source||'Fonte')}</span><span>${age(x.published_at||x.published)}</span><span>${esc(x.impact_label||x.impact||'')}</span></div><div class="why">${esc(x.why_it_matters||x.why||'')}</div><div class="news-actions"><button class="secondary mini" data-monitor-news="${i}">Monitora</button><button class="primary mini" data-analyze-news="${i}">Analizza insieme</button></div></article>`}).join(''):'<div class="muted">Nessuna news direttamente collegata nel feed corrente.</div>';$$('#tokenNewsList [data-monitor-news]').forEach(x=>x.onclick=()=>addNewsToMonitor(Number(x.dataset.monitorNews),false));$$('#tokenNewsList [data-analyze-news]').forEach(x=>x.onclick=()=>addNewsToMonitor(Number(x.dataset.analyzeNews),true))}

async function showChangesV18(){const box=$('changesBox');box.hidden=false;if(!state.watch.length){box.innerHTML='<div class="muted">Nessun token monitorato.</div>';return}box.innerHTML='<div class="research-loading">Confronto 24h + ricerca delle possibili influenze…</div>';const ws=state.watch.slice(0,8),rs=await Promise.allSettled(ws.map(w=>j(RESEARCH+'?type=change&address='+encodeURIComponent(w.address)+'&symbol='+encodeURIComponent(w.symbol||'')+'&name='+encodeURIComponent(w.name||''))));box.innerHTML=rs.map((r,i)=>{const w=ws[i];if(r.status!=='fulfilled')return`<div class="change-intel"><b>${esc(w.symbol||w.name)}</b><p>Dati storici ancora insufficienti.</p></div>`;const d=r.value,c=d.changes||{},arts=(d.articles||[]).slice(0,3);return`<div class="change-intel"><div class="change-title"><b>${esc(w.symbol||w.name)}</b><span>copertura ${fmt(d.coverageHours,1)}h · confidenza ${Math.round(N(d.confidence)*100)}%</span></div><div class="change-metrics"><span>Prezzo ${c.price==null?'—':(c.price>=0?'+':'')+fmt(c.price,2)+'%'}</span><span>Liquidità ${c.liquidity==null?'—':(c.liquidity>=0?'+':'')+fmt(c.liquidity,2)+'%'}</span><span>Volume ${c.volume==null?'—':(c.volume>=0?'+':'')+fmt(c.volume,1)+'%'}</span><span>Rischio ${c.risk==null?'—':(c.risk>=0?'+':'')+fmt(c.risk,0)}</span></div><p>${esc(d.conclusion||'')}</p>${arts.length?`<div class="change-news">${arts.map(x=>`<a href="${esc(x.url||'#')}" target="_blank" rel="noopener">${esc(x.title)}</a>`).join('')}</div>`:''}</div>`}).join('')}

renderAlerts=function(){$('alertCount').textContent=state.alerts.length;$('alertsList').innerHTML=state.alerts.length?state.alerts.map(x=>`<div><b>${esc(x.message)}</b><br><small>${age(x.created_at)} · ${esc(x.severity||'')}</small>${x.influence_summary?`<p class="alert-why">${esc(x.influence_summary)} ${x.confidence!=null?'Confidenza '+Math.round(N(x.confidence)*100)+'%.':''}</p>`:''}${(x.related_news||[]).slice(0,2).map(n=>`<a class="alert-link" href="${esc(n.primary_url||'#')}" target="_blank" rel="noopener">${esc(n.title)}</a>`).join('')}</div>`).join(''):'<div class="muted">Nessun avviso.</div>';const last=Number(localStorage.getItem('kiber_v17_last_alert')||0),fresh=state.alerts.filter(x=>new Date(x.created_at).getTime()>last&&x.severity==='high');if(fresh.length&&'Notification'in window&&Notification.permission==='granted')new Notification('Kibernetic',{body:fresh[0].message});if(state.alerts[0])localStorage.setItem('kiber_v17_last_alert',String(new Date(state.alerts[0].created_at).getTime()))}

function v18Start(){document.title='Kibernetic BNB Intelligence V18';const eye=document.querySelector('.hero .eyebrow');if(eye)eye.textContent='BNB CHAIN INTELLIGENCE · V18';$('appStatus').textContent='V18 · MONITOR H24 + RICERCA MULTIFONTE';$('changedBtn').textContent='Cosa è cambiato e perché?';$('changedBtn').onclick=showChangesV18;ensureDossierPanel();renderDossier();v18EnsureChart();loadAlerts();if(state.news.length)renderNews();setTimeout(()=>{if(state.news.length)renderNews();renderDossier()},1200)}
setTimeout(v18Start,0);