/* Kibernetic V19 — graph-first layer, based on frozen V18 */
const V19={lib:null,chart:null,area:null,candles:null,volume:null,liquidity:null,marketCap:null,areaMarkers:null,candleMarkers:null,mode:'line',metric:'volume',detail:'simple',rows:[],period:'24h',locked:false,selectedIndex:-1,pending:null,events:[],loading:false};
const v19OldDrawHistory=drawHistory;

function v19Css(name,fallback){const v=getComputedStyle(document.body).getPropertyValue(name).trim();return v||fallback}
function v19TimeLabel(sec){return new Date(Number(sec)*1000).toLocaleString('it-IT',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function v19Clock(sec){return new Date(Number(sec)*1000).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}
function v19Hours(period){return({'24h':24,'7d':168,'1m':720,'3m':2160,'1y':8760,'3y':26280})[period]||168}
function v19ResearchHours(period){return({'24h':3,'7d':12,'1m':24,'3m':36,'1y':72,'3y':168})[period]||12}
function v19UniqueRows(a){const m=new Map();for(const r of a||[]){const t=N(r?.[0]);if(t>0)m.set(t,r)}return[...m.values()].sort((x,y)=>N(x[0])-N(y[0]))}
function v19NearestIndex(sec){if(!V19.rows.length)return-1;let best=0,dist=Infinity;for(let i=0;i<V19.rows.length;i++){const d=Math.abs(N(V19.rows[i][0])-Number(sec));if(d<dist){dist=d;best=i}}return best}
function v19Snapshot(tsMs){try{return v18NearestSnapshot(tsMs)}catch{return null}}
function v19PriceFormat(v){v=Math.abs(N(v));if(v>=100)return{type:'price',precision:2,minMove:.01};if(v>=1)return{type:'price',precision:4,minMove:.0001};if(v>=.01)return{type:'price',precision:6,minMove:.000001};return{type:'price',precision:8,minMove:.00000001}}

function v19EnsureShell(){const card=document.querySelector('#tab-chart .chart-card');if(!card||$('v19ChartShell'))return;const old=$('priceChart');
const toolbar=document.createElement('div');toolbar.className='v19-chart-toolbar';toolbar.innerHTML=`<div class="v19-segment"><button type="button" data-v19-mode="line" class="active">Linea</button><button type="button" data-v19-mode="candles">Candele</button></div><div class="v19-segment"><button type="button" data-v19-detail="simple" class="active">Semplice</button><button type="button" data-v19-detail="advanced">Avanzato</button></div><div class="v19-segment v19-advanced-only"><button type="button" data-v19-metric="volume" class="active">Volume</button><button type="button" data-v19-metric="liquidity">Liquidità</button><button type="button" data-v19-metric="marketCap">Market cap</button></div>`;
old.insertAdjacentElement('beforebegin',toolbar);
const shell=document.createElement('div');shell.id='v19ChartShell';shell.className='v19-chart-shell';shell.dataset.detail='simple';shell.innerHTML=`<div class="v19-chart-wrap"><div class="v19-chart-note"><span class="v19-live-dot"></span><span>Grafico interattivo · trascina, zooma, tocca un punto</span></div><div id="v19ChartCanvas" class="v19-chart-canvas"><div class="v19-chart-loading">Caricamento motore grafico…</div></div><div id="v19MetricMessage" class="v19-metric-empty" hidden></div></div><div id="pointInspector" class="point-inspector"><div><span>PUNTO SELEZIONATO</span><b id="pointWhen">Muovi il dito sul grafico</b><small id="pointLock">Tocca un punto per bloccarlo</small></div><div class="point-metrics"><div><span>Prezzo</span><b id="pointPrice">—</b></div><div><span>Volume candela</span><b id="pointVolume">—</b></div><div><span>Liquidità storica</span><b id="pointLiquidity">—</b></div><div><span>O / H / L</span><b id="pointOhl">—</b></div></div><div class="point-actions"><button type="button" class="primary" id="analyzePointBtn" disabled>Analizza questo momento</button><button type="button" class="secondary" id="askPointKiber" disabled>Chiedi a Kiber</button></div><div id="pointAnalysis" class="point-analysis" hidden></div><div class="v19-event-legend"><span>N · News token</span><span>K · Alert Kibernetic</span><span class="v19-advanced-only">M · Macro/Regole</span></div><div class="v19-timeline"><div class="v19-timeline-head"><h4>Timeline eventi</h4><span id="v19EventCount">0 eventi nel periodo</span></div><div id="v19TimelineList" class="v19-timeline-list"></div></div><div class="v19-attribution">Grafico realizzato con <a href="https://www.tradingview.com/" target="_blank" rel="noopener">TradingView Lightweight Charts™</a>.</div>`;
old.insertAdjacentElement('afterend',shell);
$('analyzePointBtn').onclick=()=>analyzePoint();$('askPointKiber').onclick=()=>askPointKiber();
$$('[data-v19-mode]').forEach(b=>b.onclick=()=>v19SetMode(b.dataset.v19Mode));$$('[data-v19-detail]').forEach(b=>b.onclick=()=>v19SetDetail(b.dataset.v19Detail));$$('[data-v19-metric]').forEach(b=>b.onclick=()=>v19SetMetric(b.dataset.v19Metric));
const periods=document.querySelector('.periods');if(periods&&!periods.querySelector('[data-period="3m"]')){const oneY=periods.querySelector('[data-period="1y"]'),b=document.createElement('button');b.type='button';b.dataset.period='3m';b.textContent='3M';b.onclick=()=>loadHistory('3m');periods.insertBefore(b,oneY)}
}

function v19UpdateStats(a,period){const rows=v19UniqueRows(a),close=rows.map(x=>N(x[4])).filter(x=>x>0);if(close.length<2){$('chartStory').textContent='Pochi dati per questo periodo.';return}const lo=Math.min(...close),hi=Math.max(...close),move=(close.at(-1)/close[0]-1)*100,rets=close.slice(1).map((x,i)=>x/close[i]-1),mean=rets.reduce((z,x)=>z+x,0)/(rets.length||1),vol=Math.sqrt(rets.reduce((z,x)=>z+(x-mean)**2,0)/(rets.length||1))*100;let peak=close[0],dd=0;for(const x of close){peak=Math.max(peak,x);dd=Math.min(dd,(x/peak-1)*100)}$('chartMove').textContent=(move>=0?'+':'')+fmt(move,2)+'%';$('chartMove').className=move>=0?'up':'down';$('chartRange').textContent=`${period.toUpperCase()} · ${close.length} punti · zoom attivo`;$('gDirection').textContent=Math.abs(move)<2?'Laterale':move>0?'Rialzo':'Ribasso';$('gVolatility').textContent=fmt(vol,2)+'%';$('gDrawdown').textContent=fmt(dd,2)+'%';$('gPoints').textContent=close.length;$('chartStory').textContent=`Periodo ${period.toUpperCase()}: ${move>=0?'rialzo':'ribasso'} ${fmt(Math.abs(move),2)}%, minimo ${usd(lo,6)}, massimo ${usd(hi,6)}. Trascina il grafico, usa il pinch per lo zoom e tocca un punto per bloccare data, prezzo, volume e liquidità storica.`}

drawHistory=function(a,period){v19EnsureShell();V19.period=period;V19.rows=v19UniqueRows(a);V19.pending={a:V19.rows,period};V19.locked=false;V19.selectedIndex=-1;try{V18.locked=false;V18.point=null;V18.pointResearch=null}catch{}v19UpdateStats(V19.rows,period);if(V19.lib)v19RenderChart();else if($('v19ChartCanvas'))$('v19ChartCanvas').innerHTML='<div class="v19-chart-loading">Preparazione grafico finanziario…</div>'}

loadHistory=async function(period){const t=state.selected;if(!t?.pairs?.[0]?.pairAddress)return;state.period=period;$$('.periods button').forEach(b=>b.classList.toggle('active',b.dataset.period===period));$('chartStory').textContent='Caricamento storico…';const apiPeriod=period==='3m'?'1y':period;try{const [d,m]=await Promise.all([j(DATA+'?type=history&pool='+encodeURIComponent(t.pairs[0].pairAddress)+'&period='+apiPeriod),j(MEM+'?type=history&addresses='+encodeURIComponent(t.address)+'&hours='+v19Hours(period)).catch(()=>({items:[]}))]);let a=(d.ohlcv||[]).slice().reverse();if(period==='3m')a=a.slice(-90);state.history=a;V18.memory=(m.items||[]).filter(x=>String(x.token_address).toLowerCase()===String(t.address).toLowerCase());drawHistory(a,period)}catch{$('chartStory').textContent='Storico non disponibile per questo pool o periodo.'}}

function v19SeriesData(){const rows=V19.rows;return{area:rows.map(r=>({time:N(r[0]),value:N(r[4])})),candles:rows.map(r=>({time:N(r[0]),open:N(r[1]),high:N(r[2]),low:N(r[3]),close:N(r[4])})),volume:rows.map(r=>({time:N(r[0]),value:Math.max(0,N(r[5])),color:N(r[4])>=N(r[1])?'rgba(48,200,137,.55)':'rgba(243,93,119,.55)'}))}}
function v19MemorySeries(key){const start=N(V19.rows[0]?.[0]),end=N(V19.rows.at(-1)?.[0]),m=new Map();for(const x of V18.memory||[]){const time=Math.floor(new Date(x.captured_at).getTime()/1000),value=N(x[key]);if(time>=start&&time<=end&&value>0)m.set(time,value)}return[...m].sort((a,b)=>a[0]-b[0]).map(([time,value])=>({time,value}))}

function v19RenderChart(){if(!V19.lib||!V19.rows.length)return;v19EnsureShell();const L=V19.lib,el=$('v19ChartCanvas');if(!el)return;if(V19.chart){try{V19.chart.remove()}catch{}V19.chart=null}el.innerHTML='';const text=v19Css('--muted','#8fa7bf'),grid=v19Css('--line','#24364a'),accent=v19Css('--accent','#2386ff'),up=v19Css('--up','#30c889'),down=v19Css('--down','#f35d77');
V19.chart=L.createChart(el,{autoSize:true,height:470,layout:{background:{type:L.ColorType.Solid,color:'transparent'},textColor:text,fontFamily:'Inter,ui-sans-serif,system-ui,sans-serif',panes:{separatorColor:grid,separatorHoverColor:accent,enableResize:true}},grid:{vertLines:{color:'rgba(143,167,191,.07)'},horzLines:{color:'rgba(143,167,191,.07)'}},crosshair:{mode:L.CrosshairMode.Magnet,vertLine:{color:'rgba(143,167,191,.7)',width:1,labelBackgroundColor:accent},horzLine:{color:'rgba(143,167,191,.35)',width:1,labelBackgroundColor:accent}},handleScroll:{mouseWheel:true,pressedMouseMove:true,horzTouchDrag:true,vertTouchDrag:false},handleScale:{axisPressedMouseMove:true,mouseWheel:true,pinch:true},timeScale:{borderColor:grid,timeVisible:true,secondsVisible:false,rightOffset:3,barSpacing:9,minBarSpacing:2},rightPriceScale:{borderColor:grid,scaleMargins:{top:.08,bottom:.08}},localization:{locale:'it-IT'}});
const d=v19SeriesData(),pf=v19PriceFormat(d.area.at(-1)?.value);V19.area=V19.chart.addSeries(L.AreaSeries,{priceFormat:pf,lineColor:accent,lineWidth:2,topColor:'rgba(35,134,255,.30)',bottomColor:'rgba(35,134,255,.02)',crosshairMarkerVisible:true,lastValueVisible:true,priceLineVisible:true});V19.candles=V19.chart.addSeries(L.CandlestickSeries,{priceFormat:pf,upColor:up,downColor:down,borderUpColor:up,borderDownColor:down,wickUpColor:up,wickDownColor:down,visible:false});V19.volume=V19.chart.addSeries(L.HistogramSeries,{priceFormat:{type:'volume'},lastValueVisible:false,priceLineVisible:false},1);V19.liquidity=V19.chart.addSeries(L.LineSeries,{color:'#35d6ff',lineWidth:2,priceFormat:{type:'volume'},lastValueVisible:true,priceLineVisible:false,visible:false},1);V19.marketCap=V19.chart.addSeries(L.LineSeries,{color:'#ffbd55',lineWidth:2,priceFormat:{type:'volume'},lastValueVisible:true,priceLineVisible:false,visible:false},1);V19.area.setData(d.area);V19.candles.setData(d.candles);V19.volume.setData(d.volume);V19.liquidity.setData(v19MemorySeries('liquidity_usd'));V19.marketCap.setData(v19MemorySeries('market_cap'));
try{const panes=V19.chart.panes();if(panes[0])panes[0].setHeight(330);if(panes[1])panes[1].setHeight(115)}catch{}
V19.chart.subscribeCrosshairMove(p=>{if(V19.locked||p.time==null)return;const i=v19NearestIndex(Number(p.time));if(i>=0)v19SelectIndex(i,false,false)});V19.chart.subscribeClick(p=>{const id=String(p.hoveredObjectId||'');if(id.startsWith('news:')){const i=Number(id.slice(5));if(Number.isInteger(i)){openNews(i);return}}if(p.time==null)return;const i=v19NearestIndex(Number(p.time));if(i<0)return;V19.locked=!V19.locked;try{V18.locked=V19.locked}catch{}v19SelectIndex(i,V19.locked,true);$('pointLock').textContent=V19.locked?'Punto bloccato · tocca di nuovo per sbloccare':'Tocca un punto per bloccarlo'});V19.chart.timeScale().fitContent();v19ApplyMode();v19ApplyMetric();v19RefreshEvents();v19SelectIndex(V19.rows.length-1,false,true)}

function v19SetMode(mode){V19.mode=mode==='candles'?'candles':'line';$$('[data-v19-mode]').forEach(b=>b.classList.toggle('active',b.dataset.v19Mode===V19.mode));v19ApplyMode()}
function v19ApplyMode(){if(!V19.area||!V19.candles)return;V19.area.applyOptions({visible:V19.mode==='line'});V19.candles.applyOptions({visible:V19.mode==='candles'});v19RefreshMarkers()}
function v19SetDetail(detail){V19.detail=detail==='advanced'?'advanced':'simple';const shell=$('v19ChartShell');if(shell)shell.dataset.detail=V19.detail;$$('[data-v19-detail]').forEach(b=>b.classList.toggle('active',b.dataset.v19Detail===V19.detail));if(V19.detail==='simple')v19SetMetric('volume');v19RefreshEvents()}
function v19SetMetric(metric){V19.metric=['volume','liquidity','marketCap'].includes(metric)?metric:'volume';$$('[data-v19-metric]').forEach(b=>b.classList.toggle('active',b.dataset.v19Metric===V19.metric));v19ApplyMetric()}
function v19ApplyMetric(){if(!V19.volume)return;V19.volume.applyOptions({visible:V19.metric==='volume'});V19.liquidity.applyOptions({visible:V19.metric==='liquidity'});V19.marketCap.applyOptions({visible:V19.metric==='marketCap'});const msg=$('v19MetricMessage');if(!msg)return;const count=V19.metric==='liquidity'?v19MemorySeries('liquidity_usd').length:V19.metric==='marketCap'?v19MemorySeries('market_cap').length:1;if(V19.metric!=='volume'&&count<2){msg.hidden=false;msg.textContent=V19.metric==='liquidity'?'Lo storico della liquidità parte da quando il monitor Kibernetic ha iniziato a raccoglierlo.':'Market cap storico non ancora sufficiente nel nostro archivio.'}else msg.hidden=true}

function v19SelectIndex(i,lock=false,forceCrosshair=false){const r=V19.rows[i];if(!r)return;V19.selectedIndex=i;const ts=N(r[0])*1000,open=N(r[1]),high=N(r[2]),low=N(r[3]),close=N(r[4]),volume=N(r[5]),snapshot=v19Snapshot(ts);try{V18.point={i,ts,open,high,low,close,volume,snapshot};V18.pointResearch=null}catch{}$('pointWhen').textContent=v19TimeLabel(r[0]);$('pointPrice').textContent=usd(close,8);$('pointVolume').textContent=short(volume);$('pointLiquidity').textContent=snapshot?short(snapshot.liquidity_usd):'non disponibile';$('pointOhl').textContent=`${usd(open,5)} / ${usd(high,5)} / ${usd(low,5)}`;$('analyzePointBtn').disabled=false;$('askPointKiber').disabled=false;const pa=$('pointAnalysis');if(pa&&!lock){pa.hidden=true;pa.innerHTML=''}const box=$('pointInspector');if(box){box.classList.remove('v19-pulse');void box.offsetWidth;box.classList.add('v19-pulse')}if(forceCrosshair&&V19.chart&&typeof V19.chart.setCrosshairPosition==='function'){try{V19.chart.setCrosshairPosition(close,N(r[0]),V19.mode==='candles'?V19.candles:V19.area)}catch{}}}

function v19DirectNews(n){const t=state.selected;if(!t)return false;const addr=String(t.address||'').toLowerCase(),title=String(n.title||'').toLowerCase(),sym=String(t.symbol||'').toLowerCase(),name=String(t.name||'').toLowerCase();if((n.token_addresses||[]).map(x=>String(x).toLowerCase()).includes(addr))return true;if(name.length>4&&title.includes(name))return true;if(sym.length>=3){try{return new RegExp(`\\b${sym.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'i').test(title)}catch{}}return false}
function v19EventTime(n){const x=n.published_at||n.published||n.created_at;const t=new Date(x).getTime();return Number.isFinite(t)?Math.floor(t/1000):0}
function v19RefreshEvents(){if(!V19.rows.length)return;const start=N(V19.rows[0][0]),end=N(V19.rows.at(-1)[0]),events=[];for(let i=0;i<(state.news||[]).length;i++){const n=state.news[i],time=v19EventTime(n);if(time<start||time>end)continue;const direct=v19DirectNews(n),cat=n.category||'token';if(!direct&&!(V19.detail==='advanced'&&(cat==='macro'||cat==='policy')))continue;events.push({kind:direct?'news':'macro',time,title:n.title||'Notizia',newsIndex:i})}const addr=String(state.selected?.address||'').toLowerCase();for(const a of state.alerts||[]){const time=v19EventTime(a);if(time>=start&&time<=end&&(!a.token_address||String(a.token_address).toLowerCase()===addr))events.push({kind:'alert',time,title:a.message||a.event_type||'Alert Kibernetic'})}events.sort((a,b)=>a.time-b.time);V19.events=events.slice(-24);v19RefreshMarkers();v19RenderTimeline()}
function v19RefreshMarkers(){if(!V19.lib||!V19.area||!V19.candles)return;const accent=v19Css('--accent2','#35d6ff'),warn=v19Css('--warn','#ffbd55'),down=v19Css('--down','#f35d77'),markers=V19.events.map((e,k)=>{const i=v19NearestIndex(e.time),time=N(V19.rows[i]?.[0]);return{time,position:e.kind==='alert'?'belowBar':'aboveBar',shape:e.kind==='alert'?'arrowUp':'circle',color:e.kind==='alert'?down:e.kind==='macro'?warn:accent,text:e.kind==='alert'?'K':e.kind==='macro'?'M':'N',size:1.25,id:e.newsIndex!=null?'news:'+e.newsIndex:'alert:'+k}}).filter(x=>x.time>0);try{if(!V19.areaMarkers)V19.areaMarkers=V19.lib.createSeriesMarkers(V19.area,markers);else V19.areaMarkers.setMarkers(markers);if(!V19.candleMarkers)V19.candleMarkers=V19.lib.createSeriesMarkers(V19.candles,markers);else V19.candleMarkers.setMarkers(markers)}catch{}}
function v19RenderTimeline(){const list=$('v19TimelineList'),count=$('v19EventCount');if(!list||!count)return;count.textContent=V19.events.length+' eventi nel periodo';const recent=[...V19.events].reverse().slice(0,10);list.innerHTML=recent.length?recent.map((e,i)=>`<button type="button" class="v19-event-row" data-v19-time="${e.time}" ${e.newsIndex!=null?`data-v19-news="${e.newsIndex}"`:''}><time>${v19Clock(e.time)}</time><span class="v19-event-tag">${e.kind==='alert'?'K':e.kind==='macro'?'M':'N'}</span><b>${esc(e.title)}</b></button>`).join(''):'<div class="muted">Nessun evento sufficientemente pertinente in questo periodo.</div>';$$('[data-v19-time]').forEach(b=>b.onclick=()=>{const i=v19NearestIndex(Number(b.dataset.v19Time));if(i>=0){V19.locked=true;V18.locked=true;v19SelectIndex(i,true,true);$('pointLock').textContent='Punto bloccato dalla timeline · tocca il grafico per sbloccare';$('pointInspector').scrollIntoView({behavior:'smooth',block:'nearest'})}})}

function v19ApplyTheme(){if(!V19.chart)return;try{V19.chart.applyOptions({layout:{textColor:v19Css('--muted','#8fa7bf')},rightPriceScale:{borderColor:v19Css('--line','#24364a')}})}catch{}}
function v19Status(){const el=$('appStatus');if(!el)return;const online=$('monitorState')?.textContent==='Online';el.textContent=online?'V19 · GRAFICO PRO · MONITOR H24':'V19 · GRAFICO PRO'}

(async function v19Boot(){v19EnsureShell();const status=$('appStatus');if(status)new MutationObserver(v19Status).observe(status,{childList:true,characterData:true,subtree:true});new MutationObserver(v19ApplyTheme).observe(document.body,{attributes:true,attributeFilter:['class']});v19Status();try{V19.loading=true;V19.lib=await import('https://cdn.jsdelivr.net/npm/lightweight-charts@5.2.1/+esm');V19.loading=false;if(V19.pending||state.history?.length)v19RenderChart();else if($('v19ChartCanvas'))$('v19ChartCanvas').innerHTML='<div class="v19-chart-loading">Scegli un token per aprire il grafico.</div>'}catch(e){V19.loading=false;const shell=$('v19ChartShell');if(shell)shell.style.display='none';const old=$('priceChart');if(old)old.style.setProperty('display','block','important');if(V19.pending)v19OldDrawHistory(V19.pending.a,V19.pending.period);$('chartStory').textContent='Grafico avanzato non caricato: uso temporaneamente il grafico V18.'}})();