(()=>{
  const CATALOG='https://iytjxruxpvwjjhbndkzo.supabase.co/functions/v1/kibernetic-catalog';
  const V={items:[],visible:80,sort:'rank',mode:'catalog',searching:false,source:'CoinGecko'};
  const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
  const get=async url=>{const r=await fetch(url);if(!r.ok)throw new Error(String(r.status));return r.json()};
  const money=v=>Number.isFinite(+v)?'$'+(+v).toLocaleString('it-IT',{maximumFractionDigits:+v<1?8:2}):'—';
  const compact=v=>{v=Number(v)||0;return v>=1e12?'$'+(v/1e12).toFixed(2)+'T':v>=1e9?'$'+(v/1e9).toFixed(2)+'B':v>=1e6?'$'+(v/1e6).toFixed(2)+'M':v>=1e3?'$'+(v/1e3).toFixed(1)+'K':money(v)};
  const pct=v=>`${Number(v)>=0?'+':''}${Number(v||0).toLocaleString('it-IT',{maximumFractionDigits:2})}%`;
  const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const byAddr=a=>V.items.find(x=>String(x.address||'').toLowerCase()===String(a||'').toLowerCase());
  const sectorFor=x=>{try{return sectorGuess({baseToken:{name:x.name,symbol:x.symbol}})}catch{return'Altro'}};
  let marketObserver=null;

  function loadStyle(){if(q('link[data-v21-market]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='v21-market.css?v=21a';l.dataset.v21Market='1';document.head.appendChild(l)}
  function setVersion(){document.title='Kiber BNB Intelligence V21';const s=document.getElementById('v20Status')||document.getElementById('v21Status');if(s){s.id='v21Status';s.textContent='V21 · KIBER BNB INTELLIGENCE · CATALOGO MERCATO'}const eye=q('.hero .eyebrow');if(eye)eye.textContent='KIBER BNB INTELLIGENCE · V21'}

  function buildTools(){const body=q('#section-market .section-body');if(!body||q('#v21CatalogTools'))return;const head=q('#section-market .section-head h2'),desc=q('#section-market .section-head p');if(head)head.textContent='Catalogo Mercato';if(desc)desc.textContent='Classifica ordinata, loghi originali, capitalizzazione e accesso diretto all’analisi BNB Chain.';const box=document.createElement('div');box.id='v21CatalogTools';box.innerHTML=`<div class="market-catalog-tools"><div class="market-catalog-tabs"><button type="button" data-v21-mode="catalog" class="active">Classifica BNB</button><button type="button" data-v21-mode="chain">Mercato on-chain</button></div><select class="catalog-sort" id="v21CatalogSort"><option value="rank">Posizione globale</option><option value="marketCap">Capitalizzazione</option><option value="volume24">Volume 24h</option><option value="change24">Variazione 24h</option></select></div><div class="catalog-source" id="v21CatalogSource"><span><b>Fonte catalogo:</b> CoinGecko · Analisi: BNB Chain</span><span id="v21CatalogMeta">Caricamento…</span></div>`;body.insertBefore(box,body.firstChild);qa('[data-v21-mode]',box).forEach(b=>b.onclick=()=>setMode(b.dataset.v21Mode));q('#v21CatalogSort').onchange=e=>{V.sort=e.target.value;renderCatalog()}}

  function sortedItems(items=V.items){const a=[...items];if(V.sort==='marketCap')a.sort((x,y)=>(y.marketCap||0)-(x.marketCap||0));else if(V.sort==='volume24')a.sort((x,y)=>(y.volume24||0)-(x.volume24||0));else if(V.sort==='change24')a.sort((x,y)=>(y.change24||0)-(x.change24||0));else a.sort((x,y)=>(x.rank??999999)-(y.rank??999999));return a}

  function rowHtml(x){const c=Number(x.change24||0),sec=sectorFor(x),rank=x.rank?`#${x.rank}`:'—',logo=x.image?`<img class="token-logo" src="${safe(x.image)}" alt="Logo ${safe(x.symbol)}" loading="lazy" decoding="async" referrerpolicy="no-referrer">`:`<span class="token-logo-fallback">${safe(String(x.symbol||'?').slice(0,3))}</span>`;return `<div class="token-row catalog-row${x.onBsc?'':' catalog-not-bsc'}" data-v21-address="${safe(x.address)}" data-v21-id="${safe(x.id)}"><div class="catalog-rank">${rank}</div><div class="token-name"><span class="token-logo-wrap">${logo}</span><b>${safe(x.name)} <span class="catalog-symbol">${safe(x.symbol)}</span></b><small>${safe(sec)} · ${safe(x.representation||'BNB Chain')}</small></div><div class="catalog-metric catalog-price"><small>Prezzo</small><b>${money(x.price)}</b></div><div class="catalog-metric catalog-cap"><small>Capitalizzazione</small><b>${compact(x.marketCap)}</b></div><div class="catalog-metric catalog-volume"><small>Volume 24h</small><b>${compact(x.volume24)}</b></div><div class="catalog-metric catalog-change"><small>24h</small><b class="${c>=0?'up':'down'}">${pct(c)}</b></div><button class="catalog-analyze" type="button">Analizza</button></div>`}

  function bindRows(){qa('#marketList [data-v21-address]').forEach(r=>{const go=e=>{e?.stopPropagation();const a=r.dataset.v21Address;if(a)openToken(a)};r.onclick=go;r.querySelector('.catalog-analyze')?.addEventListener('click',go)})}
  function observeMarket(){if(marketObserver)marketObserver.disconnect();const list=document.getElementById('marketList');if(!list)return;marketObserver=new MutationObserver(()=>{if(V.mode==='catalog'&&!q('#marketList .catalog-row'))setTimeout(()=>renderCatalog(),0)});marketObserver.observe(list,{childList:true})}
  function renderCatalog(items=V.items){if(V.mode!=='catalog')return;const list=document.getElementById('marketList');if(!list)return;if(marketObserver)marketObserver.disconnect();const a=sortedItems(items),shown=a.slice(0,V.visible);list.innerHTML=shown.length?shown.map(rowHtml).join(''):'<div class="catalog-empty">Nessun token BNB Chain trovato nel catalogo corrente.</div>';if(a.length>shown.length){const b=document.createElement('button');b.className='secondary catalog-load';b.type='button';b.textContent=`Carica altri ${Math.min(80,a.length-shown.length)} token`;b.onclick=()=>{V.visible+=80;renderCatalog(items)};list.appendChild(b)}bindRows();const mc=document.getElementById('marketCount');if(mc)mc.textContent=`${a.length} classificati`;const meta=document.getElementById('v21CatalogMeta');if(meta)meta.textContent=`${shown.length}/${a.length} token visibili`;observeMarket()}

  async function loadCatalog(){V.mode='catalog';V.searching=false;document.body.classList.add('v21-mode-catalog');document.body.classList.remove('v21-mode-chain');qa('[data-v21-mode]').forEach(b=>b.classList.toggle('active',b.dataset.v21Mode==='catalog'));const list=document.getElementById('marketList');if(list)list.innerHTML='<div class="muted">Caricamento classifica di mercato…</div>';try{const d=await get(CATALOG+'?type=bsc&pages=4');V.items=d.items||[];V.visible=80;V.source=d.source||'CoinGecko';const src=document.getElementById('v21CatalogSource');if(src)src.firstElementChild.innerHTML='<b>Fonte catalogo:</b> CoinGecko · posizioni globali e capitalizzazione · analisi on-chain BNB Chain';renderCatalog()}catch(e){if(list)list.innerHTML='<div class="catalog-empty">Catalogo CoinGecko temporaneamente non disponibile. Puoi usare “Mercato on-chain” senza dati inventati.</div>';const meta=document.getElementById('v21CatalogMeta');if(meta)meta.textContent='Fonte non disponibile'}}

  function setMode(mode){V.mode=mode==='chain'?'chain':'catalog';qa('[data-v21-mode]').forEach(b=>b.classList.toggle('active',b.dataset.v21Mode===V.mode));document.body.classList.toggle('v21-mode-catalog',V.mode==='catalog');document.body.classList.toggle('v21-mode-chain',V.mode==='chain');if(V.mode==='catalog')renderCatalog();else{if(marketObserver)marketObserver.disconnect();try{applyFilters()}catch{try{renderMarket()}catch{}}const mc=document.getElementById('marketCount');if(mc)mc.textContent=(state.filtered?.length||state.market?.length||0)+' on-chain'}}

  async function v21Search(){const input=document.getElementById('tokenSearch'),text=input?.value.trim()||'';if(!text)return;if(/^0x[a-fA-F0-9]{40}$/.test(text)){V.mode='chain';setMode('chain');return legacySearch()}V.mode='catalog';document.body.classList.add('v21-mode-catalog');document.body.classList.remove('v21-mode-chain');qa('[data-v21-mode]').forEach(b=>b.classList.toggle('active',b.dataset.v21Mode==='catalog'));const list=document.getElementById('marketList');if(list)list.innerHTML='<div class="muted">Ricerca nel catalogo…</div>';try{const d=await get(CATALOG+'?type=find&q='+encodeURIComponent(text)),all=d.items||[],bsc=all.filter(x=>x.onBsc);if(bsc.length){V.searching=true;V.items=[...new Map([...bsc,...V.items].map(x=>[x.id,x])).values()];V.visible=Math.max(80,bsc.length);if(list){list.innerHTML='<div class="catalog-search-note">Risultati CoinGecko disponibili su BNB Chain.</div>'+bsc.map(rowHtml).join('');bindRows()}const mc=document.getElementById('marketCount');if(mc)mc.textContent=bsc.length+' risultati';const meta=document.getElementById('v21CatalogMeta');if(meta)meta.textContent='Ricerca CoinGecko';return}}catch{}V.mode='chain';setMode('chain');await legacySearch()}

  function decorateLab(){const t=state.selected;if(!t)return;const x=byAddr(t.address);const sub=document.getElementById('labSub');if(!sub)return;let c=q('.catalog-context',sub.parentElement);if(!x){c?.remove();return}if(!c){c=document.createElement('div');c.className='catalog-context';sub.insertAdjacentElement('afterend',c)}c.innerHTML=`<span>Posizione globale <b>${x.rank?'#'+x.rank:'—'}</b></span><span>Capitalizzazione <b>${compact(x.marketCap)}</b></span><span>Volume globale 24h <b>${compact(x.volume24)}</b></span><span>Fonte <b>CoinGecko</b></span>`}

  let legacySearch=null,legacyOpen=null,legacyRenderMarket=null;
  function wire(){legacySearch=searchToken;legacyOpen=openToken;legacyRenderMarket=renderMarket;openToken=async function(address){await legacyOpen(address);decorateLab()};renderMarket=function(){if(V.mode==='chain')legacyRenderMarket()};const sb=document.getElementById('searchBtn'),si=document.getElementById('tokenSearch');if(sb)sb.onclick=v21Search;if(si)si.onkeydown=e=>{if(e.key==='Enter')v21Search()}}

  function boot(){loadStyle();setVersion();buildTools();wire();loadCatalog()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();