(()=>{
const V='26.9',$=id=>document.getElementById(id),q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const n=v=>v===null||v===undefined||v===''?null:(Number.isFinite(Number(v))?Number(v):null);
const money=v=>{v=n(v);if(v===null)return'—';const a=Math.abs(v);if(a>=1e9)return'$'+(v/1e9).toFixed(2)+'B';if(a>=1e6)return'$'+(v/1e6).toFixed(2)+'M';if(a>=1e3)return'$'+v.toLocaleString('it-IT',{maximumFractionDigits:2});return'$'+v.toLocaleString('it-IT',{maximumFractionDigits:4})};
const pct=v=>{v=n(v);return v===null?'—':`${v>=0?'+':''}${v.toLocaleString('it-IT',{maximumFractionDigits:2})}%`};
const S={chart:null,candles:null,volume:null,days:30,ready:false,source:'—',request:0,retry:null,ro:null};
function mark(){document.body.classList.add('v269');document.documentElement.dataset.kiberVersion=V;document.title='Kiber BNB Chain'}
function loadLib(){return new Promise((ok,no)=>{const timer=setTimeout(()=>no(Error('Chart library timeout')),10000);if(window.LightweightCharts){clearTimeout(timer);return ok()}const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/lightweight-charts@5.0.9/dist/lightweight-charts.standalone.production.js';s.async=true;s.onload=()=>{clearTimeout(timer);ok()};s.onerror=()=>{clearTimeout(timer);no(Error('Chart library unavailable'))};document.head.appendChild(s)})}
function destroy(){S.ro?.disconnect();S.ro=null;try{S.chart?.remove()}catch{}S.chart=S.candles=S.volume=null}
function forecastText(){const x=$('v266BnbPill');return x?.textContent?.trim()||'🟡 NEUTRALE'}
function makeShell(){const old=q('.v268-chart')||q('.v267-chart');if(!old)return false;if(old.dataset.v269==='1')return true;old.dataset.v269='1';old.className='v269-chart';old.innerHTML=`<div class="v269-head"><div><span>BNB · GRAFICO PRINCIPALE</span><h2>BNB / USDT</h2><p>Candele di mercato reali. Tocca o trascina per leggere prezzo e momento.</p></div><div class="v269-badge" id="v269Forecast">${forecastText()}</div></div><div class="v269-controls"><div class="v269-periods"><button data-v269-days="1">24H</button><button data-v269-days="7">7G</button><button data-v269-days="30" class="active">30G</button><button data-v269-days="90">90G</button><button data-v269-days="365">1A</button><button data-v269-days="1095">3A</button></div><button id="v269AskChart" class="v269-ask">Kiber: perché?</button></div><div class="v269-strip"><div><span>ULTIMO</span><b id="v269Last">—</b></div><div><span>PERIODO</span><b id="v269Change">—</b></div><div><span>MASSIMO</span><b id="v269High">—</b></div><div><span>MINIMO</span><b id="v269Low">—</b></div></div><div id="v269Chart" class="v269-stage"><div class="v269-loading">Caricamento grafico professionale…</div></div><div class="v269-foot"><span>Prezzi: <strong id="v269Source">—</strong></span><span>Grafico: <a href="https://www.tradingview.com/" target="_blank" rel="noopener">Lightweight Charts™ by TradingView</a></span></div>`;qa('[data-v269-days]',old).forEach(b=>b.onclick=()=>{S.days=+b.dataset.v269Days;qa('[data-v269-days]',old).forEach(x=>x.classList.toggle('active',x===b));refresh()});$('v269AskChart').onclick=()=>{if(window.v268OpenChat)window.v268OpenChat('Analizza il grafico attuale di BNB e spiegami in modo semplice la previsione, cosa la sostiene e cosa potrebbe cambiarla.',true);else $('v266Send')?.click()};return true}
async function fetchCandles(days){const r=await fetch(`/api/coingecko?type=bnb_ohlc&days=${days}&v=2751`,{cache:'no-store',signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error(String(r.status));const d=await r.json();return {source:d.source||'Mercato',candles: (d.candles||[]).filter(x=>n(x.t)!==null&&[x.open,x.high,x.low,x.close].every(v=>n(v)!==null)).map(x=>({time:Number(x.t),open:Number(x.open),high:Number(x.high),low:Number(x.low),close:Number(x.close),quoteVolume:n(x.quoteVolume),volume:n(x.volume)})).sort((a,b)=>a.time-b.time)} }
function metrics(a){if(!a.length)return;const first=a[0].open,last=a.at(-1).close,high=Math.max(...a.map(x=>x.high)),low=Math.min(...a.map(x=>x.low)),chg=first?((last/first)-1)*100:null;$('v269Last').textContent=money(last);$('v269Change').textContent=pct(chg);$('v269High').textContent=money(high);$('v269Low').textContent=money(low);$('v269Source').textContent=S.source;$('v269Forecast').textContent=forecastText()}
function render(a){const el=$('v269Chart');if(!el||!window.LightweightCharts)throw Error('Chart library unavailable');destroy();el.innerHTML='';const LC=window.LightweightCharts;S.chart=LC.createChart(el,{width:el.clientWidth,height:Math.max(390,Math.min(520,window.innerHeight*.54)),layout:{background:{type:'solid',color:'#04111d'},textColor:'#7895aa',fontFamily:'system-ui,-apple-system,sans-serif'},grid:{vertLines:{color:'rgba(110,150,175,.06)'},horzLines:{color:'rgba(110,150,175,.08)'}},rightPriceScale:{borderColor:'rgba(110,150,175,.15)'},timeScale:{borderColor:'rgba(110,150,175,.15)',timeVisible:S.days<=7,secondsVisible:false,barSpacing:S.days<=1?8:S.days<=7?7:S.days<=30?6:S.days<=90?5:S.days<=365?3:2},crosshair:{mode:LC.CrosshairMode?.Normal??0},localization:{locale:'it-IT',priceFormatter:p=>'$'+Number(p).toLocaleString('it-IT',{maximumFractionDigits:2})}});S.candles=S.chart.addSeries(LC.CandlestickSeries,{upColor:'#26a69a',downColor:'#ef5350',borderVisible:false,wickUpColor:'#26a69a',wickDownColor:'#ef5350',priceLineVisible:true,lastValueVisible:true});S.candles.setData(a.map(x=>({time:x.time,open:x.open,high:x.high,low:x.low,close:x.close})));S.volume=S.chart.addSeries(LC.HistogramSeries,{priceFormat:{type:'volume'},priceScaleId:'',lastValueVisible:false,priceLineVisible:false});S.volume.priceScale().applyOptions({scaleMargins:{top:.82,bottom:0}});S.volume.setData(a.map(x=>({time:x.time,value:x.quoteVolume||x.volume||0,color:x.close>=x.open?'rgba(38,166,154,.30)':'rgba(239,83,80,.28)'})));S.chart.timeScale().fitContent();S.ro=new ResizeObserver(()=>S.chart?.applyOptions({width:el.clientWidth}));S.ro.observe(el)}
async function refresh(){const el=$('v269Chart');if(!el)return;const request=++S.request,days=S.days;clearTimeout(S.retry);destroy();el.innerHTML='<div class="v269-loading">Aggiornamento dati mercato…</div>';try{const data=await fetchCandles(days);if(request!==S.request)return;const a=data.candles;if(a.length<3)throw Error('No data');S.source=data.source;metrics(a);if(!window.LightweightCharts)await loadLib();if(request!==S.request)return;render(a)}catch(e){if(request!==S.request)return;el.innerHTML='<div class="v269-error"><b>Grafico non disponibile</b><span>Riprovo automaticamente tra poco.</span></div>';S.retry=setTimeout(refresh,15000)}}
async function aiHealth(){try{const r=await fetch('/api/kiber?v=269',{cache:'no-store'}),d=await r.json();const st=$('v268Status'),mode=$('v268Mode');if(st)st.textContent=d.ai?'IA attiva':'dati live';if(mode)mode.textContent=d.ai?'IA + DATI':'DATI LIVE';document.body.dataset.kiberAi=d.ai?'on':'fallback'}catch{document.body.dataset.kiberAi='fallback'}}
function patchChat(){if(!window.v268OpenChat){window.v268OpenChat=(seed,auto)=>{const input=$('v266Ask');if(seed&&input)input.value=seed;$('v266Send')?.click()}}aiHealth()}
function auditButtons(){qa('button').forEach(b=>{if(!b.type)b.type='button'});const send=$('v266Send'),mic=$('v266Mic');if(send)send.disabled=false;if(mic)mic.disabled=false;const profile=$('profileBtn');if(profile)profile.disabled=false;qa('.v241-card').forEach(c=>c.disabled=false)}
async function boot(){mark();let tries=0;const wait=async()=>{if(makeShell()){try{await loadLib();await refresh()}catch{await refresh()}patchChat();auditButtons();setInterval(aiHealth,60000);setInterval(auditButtons,5000)}else if(tries++<40)setTimeout(wait,200)};wait()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();
})();