(()=>{
  const V='26.0',q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)],id=x=>document.getElementById(x);
  const S={chain:null,intel:null,news:null,discovery:null,homeTab:'news',tokenAddress:null,tokenIntel:null,tokenNews:null,period:'7d',aiBusy:false};
  const n=v=>v===null||v===undefined||v===''?null:(Number.isFinite(Number(v))?Number(v):null);
  const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const money=v=>{v=n(v);if(v===null)return'—';const a=Math.abs(v);if(a>=1e12)return'$'+(v/1e12).toFixed(2)+'T';if(a>=1e9)return'$'+(v/1e9).toFixed(2)+'B';if(a>=1e6)return'$'+(v/1e6).toFixed(2)+'M';if(a>=1e3)return'$'+(v/1e3).toFixed(1)+'K';return'$'+v.toLocaleString('it-IT',{maximumFractionDigits:a<1?8:2})};
  const pct=v=>{v=n(v);return v===null?'—':`${v>=0?'+':''}${v.toLocaleString('it-IT',{maximumFractionDigits:2})}%`};
  const num=(v,d=0)=>{v=n(v);return v===null?'—':v.toLocaleString('it-IT',{maximumFractionDigits:d})};
  const selected=()=>{try{return typeof state!=='undefined'?state.selected:null}catch{return null}};
  async function json(url,opt){const r=await fetch(url,opt);if(!r.ok)throw new Error(String(r.status));return r.json()}

  function marketOutlook(){
    const b=S.chain?.bnb||{},c=S.chain?.chain||{},i=S.intel?.chain||{},news=S.news?.counts||{};let score=0,why=[];
    const bm=n(b.change24),dm=n(i.dexChange1d??c.dexChange1d);
    if(bm!==null){if(bm>=3){score+=28;why.push('BNB positiva nelle 24h')}else if(bm>=1){score+=14;why.push('BNB moderatamente positiva')}else if(bm<=-3){score-=28;why.push('BNB in pressione nelle 24h')}else if(bm<=-1){score-=14;why.push('BNB moderatamente negativa')}}
    if(dm!==null){if(dm>=10){score+=22;why.push('volume DEX in accelerazione')}else if(dm>=3){score+=11;why.push('attività DEX in crescita')}else if(dm<=-10){score-=20;why.push('volume DEX in contrazione')}else if(dm<=-3){score-=10;why.push('attività DEX in calo')}}
    const nb=(news.positive||0)-(news.negative||0);score+=Math.max(-20,Math.min(20,nb*4));if(nb>=2)why.push('flusso news prevalentemente costruttivo');else if(nb<=-2)why.push('flusso news prevalentemente negativo');
    score=Math.max(-100,Math.min(100,Math.round(score)));const direction=score>=25?'Rialzista':score<=-25?'Ribassista':'Neutrale / misto';return{score,direction,why:why.slice(0,3)};
  }

  function buildHomeRadar(){
    const home=id('v241Home');if(!home||id('v26MarketRadar'))return;
    const box=document.createElement('section');box.id='v26MarketRadar';box.className='v26-market-radar';box.innerHTML=`<div class="v26-radar-top"><div class="v26-outlook"><span>STIMA MERCATO · 24-72H</span><b id="v26HomeDirection">Calcolo scenario…</b><p id="v26HomeWhy">Kiber sta incrociando prezzo BNB, attività DEX e notizie.</p><span class="v26-outlook-score" id="v26HomeScore">score —</span></div><div class="v26-radar-stat"><span>News alto impatto</span><b id="v26HighNews">—</b><small>filtrate per rilevanza</small></div><div class="v26-radar-stat"><span>Emergenti</span><b id="v26Emerging">—</b><small>low-cap da verificare</small></div><div class="v26-radar-stat"><span>Fonti</span><b>Multi</b><small>market + chain + news</small></div></div><div class="v26-radar-tabs"><button class="active" data-v26-home="news">Notizie chiave</button><button data-v26-home="discovery">Progetti emergenti</button><button data-v26-home="method">Metodo</button></div><div id="v26RadarBody" class="v26-radar-body"><div class="v26-loading">Aggiornamento radar V26…</div></div>`;
    const metrics=q('.v241-metrics',home);(metrics||q('.v241-brief',home))?.insertAdjacentElement('afterend',box);qa('[data-v26-home]',box).forEach(b=>b.onclick=()=>{S.homeTab=b.dataset.v26Home;qa('[data-v26-home]',box).forEach(x=>x.classList.toggle('active',x===b));renderHomeBody()});
  }

  async function loadHome(){
    const settled=await Promise.allSettled([json('/api/chain?v=26'),json('/api/intelligence?v=26'),json('/api/news-v26?v=26'),json('/api/discovery-v26?v=26')]);
    if(settled[0].status==='fulfilled')S.chain=settled[0].value;if(settled[1].status==='fulfilled')S.intel=settled[1].value;if(settled[2].status==='fulfilled')S.news=settled[2].value;if(settled[3].status==='fulfilled')S.discovery=settled[3].value;renderHome();
  }

  function renderHome(){
    buildHomeRadar();const o=marketOutlook();id('v26HomeDirection')&&(id('v26HomeDirection').textContent=o.direction);id('v26HomeScore')&&(id('v26HomeScore').textContent=`Kiber scenario score ${o.score>=0?'+':''}${o.score}/100`);id('v26HomeWhy')&&(id('v26HomeWhy').textContent=o.why.join(' · ')||'Segnali non ancora abbastanza convergenti.');id('v26HighNews')&&(id('v26HighNews').textContent=String(S.news?.counts?.high??0));id('v26Emerging')&&(id('v26Emerging').textContent=String((S.discovery?.candidates||[]).filter(x=>n(x.score)>=60).length));renderHomeBody();
  }

  function renderHomeBody(){
    const box=id('v26RadarBody');if(!box)return;
    if(S.homeTab==='news'){
      const a=(S.news?.items||[]).slice(0,5);box.innerHTML=a.length?`<div class="v26-home-list">${a.map(x=>`<a class="v26-home-item" href="${esc(x.url||'#')}" target="_blank" rel="noopener"><div><b>${esc(x.title)}</b><small>${esc(x.source||'Fonte')} · ${esc(x.category||'Mercato')} · ${x.ageHours===null?'':Math.round(x.ageHours)+'h fa'}</small></div><span class="v26-badge ${x.impact==='alto'?'high':x.tone==='positivo'?'pos':x.tone==='negativo'?'neg':''}">${esc(x.impact||'basso')} · ${esc(x.tone||'misto')}</span></a>`).join('')}</div><div class="v26-source-line">Tono e impatto sono filtri euristici: una notizia diventa una tesi solo se prezzo, volume, liquidità e flussi la confermano.</div>`:'<div class="v26-empty">News V26 temporaneamente non disponibili.</div>';
    }else if(S.homeTab==='discovery'){
      const a=(S.discovery?.candidates||[]).slice(0,6);box.innerHTML=a.length?`<div class="v26-home-list">${a.map(x=>`<button class="v26-home-item" data-v26-token="${esc(x.address)}"><div><b>${esc(x.symbol||'?')} · ${esc(x.name||'Progetto')}</b><small>${money(x.metrics?.marketCap)} market cap · ${money(x.metrics?.liquidityUsd)} liquidità · ${x.metrics?.ageHours===null?'età —':Math.round(x.metrics.ageHours)+'h'}</small></div><span class="v26-badge ${x.score>=75?'hot':''}">${num(x.score)}/100 · ${esc(x.label)}</span></button>`).join('')}</div><div class="v26-source-line">“Emergente” significa che i dati meritano approfondimento, non che il progetto sia sicuro. Il ranking penalizza pool troppo giovani, liquidità fragile e movimenti estremi.</div>`:'<div class="v26-empty">Nessun candidato emergente supera i filtri minimi in questo momento.</div>';qa('[data-v26-token]',box).forEach(b=>b.onclick=()=>openCandidate(b.dataset.v26Token));
    }else{
      box.innerHTML='<div class="v26-home-list"><div class="v26-home-item"><div><b>1 · Dato osservato</b><small>Prezzo, volume, liquidità, transazioni, TVL e livelli tecnici.</small></div><span class="v26-badge">FATTO</span></div><div class="v26-home-item"><div><b>2 · News e contesto</b><small>Fonte, freschezza, rilevanza e possibile canale di impatto.</small></div><span class="v26-badge">CONTESTO</span></div><div class="v26-home-item"><div><b>3 · Scenario condizionato</b><small>Rialzista, ribassista o misto con trigger e invalidazioni, mai certezza.</small></div><span class="v26-badge">STIMA</span></div></div>';
    }
  }

  function openCandidate(address){
    const marketCard=q('[data-v241-open="market"]');marketCard?.click();setTimeout(()=>{q('[data-v241-sub="analysis"]')?.click();setTimeout(()=>{if(typeof window.openToken==='function')window.openToken(address)},30)},30);
  }

  function ensureTokenPanel(){
    const content=id('labContent');if(!content||id('v26TokenIntel'))return;
    const panel=document.createElement('section');panel.id='v26TokenIntel';panel.className='v26-token-intel';panel.innerHTML=`<div class="v26-token-head"><div><span>TOKEN INTELLIGENCE · V26</span><h3 id="v26TokenTitle">Analisi avanzata</h3><p id="v26TokenMeta">Apro dati tecnici, on-chain, news e progetto.</p></div><div class="v26-token-state"><b id="v26Direction">—</b><small id="v26DirectionScore">scenario score —</small></div></div><div class="v26-token-summary"><div class="v26-sum"><span>Qualità dati/progetto</span><b id="v26Quality">—</b><small id="v26QualityLabel">—</small></div><div class="v26-sum"><span>RSI 14</span><b id="v26Rsi">—</b><small>momentum tecnico</small></div><div class="v26-sum"><span>Supporto</span><b id="v26Support">—</b><small>livello osservato</small></div><div class="v26-sum"><span>Resistenza</span><b id="v26Resistance">—</b><small>livello osservato</small></div></div><div class="v26-commandbar"><button data-v26-mode="token360">Analisi 360</button><button data-v26-mode="scenario">Scenario 24-72h</button><button data-v26-mode="newsimpact">Impatto news</button><button data-v26-mode="projectquality">Qualità progetto</button><button data-v26-mode="strategy">Strategia di monitoraggio</button></div><div class="v26-chart-card"><div class="v26-chart-title"><b>Grafico investigativo</b><div class="v26-periods"><button data-v26-period="24h">24H</button><button data-v26-period="7d" class="active">7G</button><button data-v26-period="30d">30G</button></div></div><div class="v26-chart-wrap"><svg class="v26-chart" id="v26Chart" viewBox="0 0 1000 360" preserveAspectRatio="none"></svg></div><div class="v26-chart-legend"><span><i></i>Prezzo</span><span class="ema20"><i></i>EMA20</span><span class="ema50"><i></i>EMA50</span><span class="news"><i></i>News</span></div><p class="v26-chart-story" id="v26ChartStory">Caricamento motivazioni del movimento…</p></div><div class="v26-tech-grid"><div class="v26-tech"><span>EMA20</span><b id="v26Ema20">—</b></div><div class="v26-tech"><span>EMA50</span><b id="v26Ema50">—</b></div><div class="v26-tech"><span>Volatilità</span><b id="v26Vol">—</b></div><div class="v26-tech"><span>Trend volume</span><b id="v26VolTrend">—</b></div></div><div class="v26-token-columns"><div class="v26-box"><div class="v26-box-title"><b>News collegate</b><small>impatto + conferma da verificare</small></div><div id="v26TokenNews" class="v26-news-stack"><div class="v26-loading">Caricamento news…</div></div></div><div class="v26-box"><div class="v26-box-title"><b>Prove e rischi</b><small>perché conta</small></div><div id="v26Evidence" class="v26-evidence"></div></div></div><div id="v26AiResult" class="v26-ai-result"></div><div class="v26-token-foot" id="v26TokenFoot">Le stime V26 sono scenari condizionati. Non sono certezze di prezzo né segnali automatici di acquisto/vendita.</div>`;
    const sub=q('.subnav',content);(sub||content.firstElementChild)?.insertAdjacentElement('beforebegin',panel);
    qa('[data-v26-mode]',panel).forEach(b=>b.onclick=()=>runAi(b.dataset.v26Mode,b));qa('[data-v26-period]',panel).forEach(b=>b.onclick=()=>{S.period=b.dataset.v26Period;qa('[data-v26-period]',panel).forEach(x=>x.classList.toggle('active',x===b));loadToken(S.tokenAddress,true)});
  }

  async function syncToken(){
    ensureTokenPanel();const t=selected(),address=String(t?.address||'').toLowerCase();if(!/^0x[a-f0-9]{40}$/.test(address)||address===S.tokenAddress)return;S.tokenAddress=address;S.period='7d';qa('[data-v26-period]').forEach(x=>x.classList.toggle('active',x.dataset.v26Period==='7d'));await loadToken(address,false);
  }

  async function loadToken(address,periodOnly){
    if(!address)return;const t=selected();id('v26TokenTitle')&&(id('v26TokenTitle').textContent=`${t?.name||'Token'} (${t?.symbol||'?'})`);id('v26TokenMeta')&&(id('v26TokenMeta').textContent='Aggiornamento multi-fonte in corso…');
    try{
      const base=json(`/api/token-intel-v26?address=${encodeURIComponent(address)}&period=${encodeURIComponent(S.period)}&v=26`),news=periodOnly&&S.tokenNews?Promise.resolve(S.tokenNews):json(`/api/news-v26?symbol=${encodeURIComponent(t?.symbol||'')}&name=${encodeURIComponent(t?.name||'')}&v=26`);
      const [a,b]=await Promise.allSettled([base,news]);if(a.status==='fulfilled')S.tokenIntel=a.value;if(b.status==='fulfilled')S.tokenNews=b.value;renderToken();
    }catch{if(id('v26TokenMeta'))id('v26TokenMeta').textContent='Feed V26 temporaneamente non disponibile.'}
  }

  function roughRisk(){const ql=n(S.tokenIntel?.projectQuality?.score),vol=n(S.tokenIntel?.technical?.volatility),age=n(S.tokenIntel?.outlook?.metrics?.ageHours);let r=ql===null?50:100-ql;if(vol!==null)r+=Math.min(15,vol*1.5);if(age!==null&&age<24)r+=10;return clamp(Math.round(r))}

  function renderToken(){
    const d=S.tokenIntel;if(!d)return;const t=d.token||{},o=d.outlook||{},tech=d.technical||{},qual=d.projectQuality||{};id('v26TokenTitle')&&(id('v26TokenTitle').textContent=`${t.name||'Token'} (${t.symbol||'?'})`);id('v26TokenMeta')&&(id('v26TokenMeta').textContent=`${money(t.priceUsd)} · ${pct(t.change24h)} 24h · ${money(t.liquidityUsd)} liquidità · rischio strutturale ${roughRisk()}/100`);id('v26Direction')&&(id('v26Direction').textContent=o.direction||'—');id('v26DirectionScore')&&(id('v26DirectionScore').textContent=`scenario score ${n(o.score)!==null?(o.score>=0?'+':'')+o.score+'/100':'—'} · ${o.strength||''}`);id('v26Quality')&&(id('v26Quality').textContent=n(qual.score)!==null?qual.score+'/100':'—');id('v26QualityLabel')&&(id('v26QualityLabel').textContent=qual.label||'—');id('v26Rsi')&&(id('v26Rsi').textContent=num(tech.rsi14,1));id('v26Support')&&(id('v26Support').textContent=money(tech.support));id('v26Resistance')&&(id('v26Resistance').textContent=money(tech.resistance));id('v26Ema20')&&(id('v26Ema20').textContent=money(tech.ema20));id('v26Ema50')&&(id('v26Ema50').textContent=money(tech.ema50));id('v26Vol')&&(id('v26Vol').textContent=pct(tech.volatility));id('v26VolTrend')&&(id('v26VolTrend').textContent=pct(tech.volumeTrend));renderChart();renderTokenNews();renderEvidence();const foot=id('v26TokenFoot');if(foot)foot.textContent=`Fonti: ${(d.sources||[]).join(' + ')||'feed market'} · aggiornato ${new Date(d.updatedAt||Date.now()).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}. Scenario 24-72h condizionato da trigger e invalidazioni.`;
  }

  function emaSeries(values,p){if(!values.length)return[];const k=2/(p+1),out=[values[0]];for(let i=1;i<values.length;i++)out.push(values[i]*k+out[i-1]*(1-k));return out}
  function linePath(vals,x,y){return vals.map((v,i)=>`${i?'L':'M'} ${x(i)} ${y(v)}`).join(' ')}
  function renderChart(){
    const svg=id('v26Chart'),d=S.tokenIntel;if(!svg||!d)return;let candles=(d.technical?.candles||[]).filter(x=>Array.isArray(x)&&x.length>=6).sort((a,b)=>a[0]-b[0]);if(!candles.length){svg.innerHTML='<text x="50" y="80" fill="#7793a8">Storico non disponibile</text>';return}if(candles.length>90){const step=Math.ceil(candles.length/90);candles=candles.filter((_,i)=>i%step===0||i===candles.length-1)}
    const W=1000,H=360,L=48,R=18,T=24,B=38,highs=candles.map(c=>n(c[2])).filter(v=>v!==null),lows=candles.map(c=>n(c[3])).filter(v=>v!==null),closes=candles.map(c=>n(c[4])||0),lo=Math.min(...lows),hi=Math.max(...highs),range=hi-lo||1,x=i=>L+i/(Math.max(1,candles.length-1))*(W-L-R),y=v=>T+(hi-v)/range*(H-T-B),cw=Math.max(2,Math.min(8,(W-L-R)/candles.length*.62));let out='';
    for(let g=0;g<=4;g++){const yy=T+g*(H-T-B)/4,val=hi-g*range/4;out+=`<line x1="${L}" y1="${yy}" x2="${W-R}" y2="${yy}" stroke="rgba(92,145,181,.12)" stroke-width="1"/><text x="4" y="${yy+3}" fill="#5f7d94" font-size="10">${esc(money(val))}</text>`}
    candles.forEach((c,i)=>{const o=n(c[1]),h=n(c[2]),l=n(c[3]),cl=n(c[4]),v=n(c[5]);if([o,h,l,cl].some(z=>z===null))return;const up=cl>=o,col=up?'#63dda4':'#ff8f88',xx=x(i),yo=y(o),yc=y(cl);out+=`<line x1="${xx}" y1="${y(h)}" x2="${xx}" y2="${y(l)}" stroke="${col}" stroke-width="1"/><rect x="${xx-cw/2}" y="${Math.min(yo,yc)}" width="${cw}" height="${Math.max(1,Math.abs(yc-yo))}" rx="1" fill="${col}" opacity=".8"><title>${new Date(Number(c[0])*1000).toLocaleString('it-IT')} · O ${o} H ${h} L ${l} C ${cl} · Vol ${v}</title></rect>`});
    const e20=emaSeries(closes,20),e50=emaSeries(closes,50);out+=`<path d="${linePath(e20,x,y)}" fill="none" stroke="#ffd073" stroke-width="2" opacity=".85"/><path d="${linePath(e50,x,y)}" fill="none" stroke="#bb8cff" stroke-width="2" opacity=".8"/>`;
    const sup=n(d.technical?.support),res=n(d.technical?.resistance);if(sup!==null&&sup>=lo&&sup<=hi)out+=`<line x1="${L}" y1="${y(sup)}" x2="${W-R}" y2="${y(sup)}" stroke="#63dda4" stroke-width="1.4" stroke-dasharray="8 7" opacity=".65"/><text x="${W-150}" y="${y(sup)-4}" fill="#63dda4" font-size="10">supporto ${esc(money(sup))}</text>`;if(res!==null&&res>=lo&&res<=hi)out+=`<line x1="${L}" y1="${y(res)}" x2="${W-R}" y2="${y(res)}" stroke="#ff8f88" stroke-width="1.4" stroke-dasharray="8 7" opacity=".65"/><text x="${W-160}" y="${y(res)-4}" fill="#ff8f88" font-size="10">resistenza ${esc(money(res))}</text>`;
    const t0=Number(candles[0][0])*1000,t1=Number(candles.at(-1)[0])*1000;for(const nw of (S.tokenNews?.items||[]).slice(0,10)){const ts=Date.parse(nw.published||'');if(!Number.isFinite(ts)||ts<t0||ts>t1)continue;const xx=L+(ts-t0)/(t1-t0||1)*(W-L-R);out+=`<line x1="${xx}" y1="${T}" x2="${xx}" y2="${H-B}" stroke="#ff9b91" stroke-width="1" opacity=".22"/><circle cx="${xx}" cy="${T+9}" r="4" fill="#ff9b91"><title>${esc(nw.title)}</title></circle>`}
    svg.innerHTML=out;const drivers=d.outlook?.drivers||[],warnings=d.outlook?.warnings||[],topNews=(S.tokenNews?.items||[])[0];id('v26ChartStory')&&(id('v26ChartStory').textContent=`Movimento: ${drivers.length?drivers.join(', '):'nessuna conferma forte'}${warnings.length?'. Fattori contrari: '+warnings.join(', '):''}${topNews?'. News più rilevante: '+topNews.title+' ('+topNews.impact+', '+topNews.tone+').':''}`);
  }

  function renderTokenNews(){const box=id('v26TokenNews');if(!box)return;const a=(S.tokenNews?.items||[]).filter(x=>x.relevance==='token'||x.relevance==='bnb').slice(0,6);box.innerHTML=a.length?a.map(x=>`<div class="v26-news-row"><b>${esc(x.title)}</b><small>${esc(x.source)} · ${esc(x.impact)} · ${esc(x.tone)} · ${esc(x.trust)}</small></div>`).join(''):'<div class="v26-empty">Nessuna news con collegamento diretto abbastanza forte. Meglio un vuoto che una causalità inventata.</div>'}
  function renderEvidence(){const box=id('v26Evidence'),d=S.tokenIntel;if(!box||!d)return;const good=[...(d.outlook?.drivers||[]),...(d.projectQuality?.positives||[])].slice(0,5),bad=[...(d.outlook?.warnings||[]),...(d.projectQuality?.risks||[])].slice(0,5);let h=good.map(x=>`<div class="v26-evidence-row good"><b>${esc(x)}</b><small>elemento favorevole / conferma</small></div>`).join('')+bad.map(x=>`<div class="v26-evidence-row risk"><b>${esc(x)}</b><small>rischio / elemento contrario</small></div>`).join('');if(d.holders?.available)h+=`<div class="v26-evidence-row"><b>Top 5 holder: ${pct(d.holders.top5Pct)} · Top 20: ${pct(d.holders.top20Pct)}</b><small>${esc(d.holders.source||'holder feed')}</small></div>`;else h+=`<div class="v26-evidence-row"><b>Holder intelligence: dato non disponibile</b><small>${esc(d.holders?.reason||'API non configurata')}</small></div>`;box.innerHTML=h||'<div class="v26-empty">Evidenze insufficienti.</div>'}

  function localAi(mode){const d=S.tokenIntel||{},o=d.outlook||{},qv=d.projectQuality||{},nw=(S.tokenNews?.items||[]).slice(0,3);if(mode==='scenario')return `Scenario ${o.direction||'misto'} (${o.strength||'debole'}, score ${o.score??'—'}/100).\nConferme: ${(o.drivers||[]).join(', ')||'nessuna forte'}.\nContraddizioni: ${(o.warnings||[]).join(', ')||'nessuna evidente'}.\nTrigger rialzista: ${o.triggers?.bullish||'—'}.\nTrigger ribassista: ${o.triggers?.bearish||'—'}.\nInvalidazione: ${o.triggers?.invalidation||'—'}.`;if(mode==='newsimpact')return nw.length?nw.map(x=>`${x.impact?.toUpperCase()||''} · ${x.tone||''} · ${x.title}`).join('\n\n'):'Nessuna notizia abbastanza rilevante nel feed corrente.';if(mode==='projectquality')return `Qualità osservabile ${qv.score??'—'}/100 · ${qv.label||'—'}.\nPunti forti: ${(qv.positives||[]).join(', ')||'dati insufficienti'}.\nRischi: ${(qv.risks||[]).join(', ')||'nessuno misurato'}.`;return `Quadro V26: ${o.direction||'misto'} · qualità ${qv.score??'—'}/100 · rischio strutturale ${roughRisk()}/100. Usa i trigger e le invalidazioni, non lo score isolato.`}

  async function runAi(mode,button){
    if(S.aiBusy||!S.tokenIntel)return;S.aiBusy=true;qa('[data-v26-mode]').forEach(x=>x.classList.toggle('active',x===button));const out=id('v26AiResult');if(out){out.className='v26-ai-result show loading';out.textContent='Kiber sta incrociando tecnico, on-chain, news e progetto…'}
    const prompts={token360:'Esegui Analisi 360 completa del token con scenari, prove, contraddizioni, rischi e prossimi controlli.',scenario:'Costruisci gli scenari 24-72h rialzista, ribassista e laterale con trigger e invalidazioni.',newsimpact:'Analizza le nuove notizie: quali possono incidere davvero su questo token e quali non sono confermate dal mercato?',projectquality:'Valuta la qualità osservabile del progetto e spiega perché può essere interessante oppure fragile, soprattutto se la capitalizzazione è bassa.',strategy:'Costruisci una strategia di monitoraggio: condizioni da controllare, conferme, invalidazioni, rischio, volume, liquidità, holder e news. Niente ordini automatici di acquisto/vendita.'};
    try{const payload={analysisMode:mode,message:prompts[mode],token:selected(),tokenIntel:S.tokenIntel,marketNews:S.tokenNews,discovery:S.discovery,chain:S.chain?.chain,bnb:S.chain?.bnb,intelligence:S.intel};const r=await json('/api/kiber',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(out){out.className='v26-ai-result show';out.textContent=r.answer||localAi(mode)}}catch{if(out){out.className='v26-ai-result show';out.textContent=localAi(mode)+'\n\nAI server non disponibile: mostrata lettura deterministica V26.'}}finally{S.aiBusy=false;qa('[data-v26-mode]').forEach(x=>x.classList.remove('active'))}
  }

  function brand(){document.documentElement.dataset.kiberVersion=V;document.title='Kiber BNB Chain';const st=q('.brand-live');if(st){st.hidden=true;st.style.display='none'}const sm=q('.brand-copy small');if(sm)sm.textContent='BNB Chain';const mark=q('.brand-mark');if(mark)mark.src='assets/kiber-logo.svg?v=26'}
  function boot(){brand();buildHomeRadar();ensureTokenPanel();loadHome();syncToken();setInterval(syncToken,900);setInterval(loadHome,180000);setTimeout(brand,700)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
